-- Generated by scripts/generate_initial_ddl.py. Do not edit by hand.
-- Source: docs/02.architecture/02.data-architecture/03.physical-model

CREATE TABLE tb_sys_user (
    user_id varchar(26) NOT NULL,
    emp_id varchar(26),
    login_id varchar(26) NOT NULL,
    user_nm varchar(100) NOT NULL,
    email_addr varchar(100),
    mobile_no varchar(20),
    acnt_status_cd varchar(20) NOT NULL,
    pwd_hash_val varchar(255) NOT NULL,
    pwd_chg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    login_fail_cnt integer DEFAULT 0 NOT NULL,
    inactive_dtm timestamp,
    last_login_dtm timestamp,
    pwd_init_req_yn char(1) DEFAULT 'Y' NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    inactive_rsn_cd varchar(20),
    CONSTRAINT pk_tb_sys_user PRIMARY KEY (user_id),
    CONSTRAINT ck_tb_sys_user_02 CHECK (pwd_init_req_yn in ('Y','N')),
    CONSTRAINT ck_tb_sys_user_03 CHECK (del_yn in ('Y','N')),
    CONSTRAINT ck_tb_sys_user_04 CHECK ((acnt_status_cd = 'ACTIVE' and inactive_rsn_cd is null and inactive_dtm is null) or (acnt_status_cd = 'INACTIVE' and inactive_rsn_cd is not null and inactive_dtm is not null))
);

COMMENT ON TABLE tb_sys_user IS 'BMS 사용자 계정 기본정보와 인증 및 계정 잠금정보';
COMMENT ON COLUMN tb_sys_user.user_id IS '사용자 식별자';
COMMENT ON COLUMN tb_sys_user.emp_id IS '연계된 내부 직원 식별자';
COMMENT ON COLUMN tb_sys_user.login_id IS '로그인에 사용하는 식별자';
COMMENT ON COLUMN tb_sys_user.user_nm IS '사용자 표시 명칭';
COMMENT ON COLUMN tb_sys_user.email_addr IS '사용자 이메일 주소';
COMMENT ON COLUMN tb_sys_user.mobile_no IS '사용자 휴대전화 번호';
COMMENT ON COLUMN tb_sys_user.acnt_status_cd IS '계정 상태 코드';
COMMENT ON COLUMN tb_sys_user.pwd_hash_val IS '비밀번호 해시값';
COMMENT ON COLUMN tb_sys_user.pwd_chg_dtm IS '최근 비밀번호 변경 일시';
COMMENT ON COLUMN tb_sys_user.login_fail_cnt IS '연속 로그인 실패 건수';
COMMENT ON COLUMN tb_sys_user.inactive_dtm IS '계정 비활성 전환 일시';
COMMENT ON COLUMN tb_sys_user.last_login_dtm IS '마지막 로그인 성공 일시';
COMMENT ON COLUMN tb_sys_user.pwd_init_req_yn IS '최초 로그인 시 비밀번호 변경 필요 여부';
COMMENT ON COLUMN tb_sys_user.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_sys_user.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_sys_user.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_sys_user.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_sys_user.del_yn IS '논리 삭제 여부';
COMMENT ON COLUMN tb_sys_user.inactive_rsn_cd IS '계정 비활성 전환 원인 코드';

CREATE TABLE tb_sys_role (
    role_id varchar(26) NOT NULL,
    role_nm varchar(100) NOT NULL,
    role_desc varchar(500),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sys_role PRIMARY KEY (role_id),
    CONSTRAINT ck_tb_sys_role_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sys_role IS '시스템 접근권한 부여 단위';
COMMENT ON COLUMN tb_sys_role.role_id IS '역할 식별자';
COMMENT ON COLUMN tb_sys_role.role_nm IS '역할 명칭';
COMMENT ON COLUMN tb_sys_role.role_desc IS '역할에 대한 설명';
COMMENT ON COLUMN tb_sys_role.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_sys_role.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_sys_role.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_sys_role.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_sys_role.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_sys_user_role_rel (
    user_id varchar(26) NOT NULL,
    role_id varchar(26) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    CONSTRAINT pk_tb_sys_user_role_rel PRIMARY KEY (user_id, role_id)
);

COMMENT ON TABLE tb_sys_user_role_rel IS '사용자와 역할의 매핑 정보';
COMMENT ON COLUMN tb_sys_user_role_rel.user_id IS '사용자 식별자';
COMMENT ON COLUMN tb_sys_user_role_rel.role_id IS '역할 식별자';
COMMENT ON COLUMN tb_sys_user_role_rel.reg_id IS '관계 등록자 식별자';
COMMENT ON COLUMN tb_sys_user_role_rel.reg_dtm IS '관계 등록 일시';

CREATE TABLE tb_sys_menu (
    menu_id varchar(26) NOT NULL,
    up_menu_id varchar(26),
    menu_nm varchar(100) NOT NULL,
    menu_url varchar(300),
    sort_seq integer DEFAULT 0 NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sys_menu PRIMARY KEY (menu_id),
    CONSTRAINT ck_tb_sys_menu_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sys_menu IS '시스템 메뉴 정보';
COMMENT ON COLUMN tb_sys_menu.menu_id IS '메뉴 식별자';
COMMENT ON COLUMN tb_sys_menu.up_menu_id IS '상위 메뉴 식별자';
COMMENT ON COLUMN tb_sys_menu.menu_nm IS '메뉴 명칭';
COMMENT ON COLUMN tb_sys_menu.menu_url IS '메뉴 이동 URL';
COMMENT ON COLUMN tb_sys_menu.sort_seq IS '동일 계층 내 표시 순서';
COMMENT ON COLUMN tb_sys_menu.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_sys_menu.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_sys_menu.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_sys_menu.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_sys_menu.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_sys_role_menu_perm_rel (
    role_id varchar(26) NOT NULL,
    menu_id varchar(26) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    CONSTRAINT pk_tb_sys_role_menu_perm_rel PRIMARY KEY (role_id, menu_id)
);

COMMENT ON TABLE tb_sys_role_menu_perm_rel IS '역할별 메뉴 접근권한';
COMMENT ON COLUMN tb_sys_role_menu_perm_rel.role_id IS '역할 식별자';
COMMENT ON COLUMN tb_sys_role_menu_perm_rel.menu_id IS '메뉴 식별자';
COMMENT ON COLUMN tb_sys_role_menu_perm_rel.reg_id IS '권한 등록자 식별자';
COMMENT ON COLUMN tb_sys_role_menu_perm_rel.reg_dtm IS '권한 등록 일시';

CREATE TABLE tb_sys_org (
    org_id varchar(26) NOT NULL,
    up_org_id varchar(26),
    org_nm varchar(100) NOT NULL,
    org_type_cd varchar(20) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sys_org PRIMARY KEY (org_id),
    CONSTRAINT ck_tb_sys_org_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sys_org IS '회사 조직 및 부서 정보';
COMMENT ON COLUMN tb_sys_org.org_id IS '조직 식별자';
COMMENT ON COLUMN tb_sys_org.up_org_id IS '상위 조직 식별자';
COMMENT ON COLUMN tb_sys_org.org_nm IS '조직 명칭';
COMMENT ON COLUMN tb_sys_org.org_type_cd IS '조직 유형 코드';
COMMENT ON COLUMN tb_sys_org.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_sys_org.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_sys_org.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_sys_org.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_sys_org.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_com_code_grp (
    cd_grp_id varchar(26) NOT NULL,
    cd_grp_nm varchar(100) NOT NULL,
    cd_grp_desc_cont text,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_com_code_grp PRIMARY KEY (cd_grp_id),
    CONSTRAINT ck_tb_com_code_grp_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_com_code_grp IS '공통코드 그룹 정보';
COMMENT ON COLUMN tb_com_code_grp.cd_grp_id IS '코드 그룹 식별자';
COMMENT ON COLUMN tb_com_code_grp.cd_grp_nm IS '코드 그룹 명칭';
COMMENT ON COLUMN tb_com_code_grp.cd_grp_desc_cont IS '코드 그룹 설명';
COMMENT ON COLUMN tb_com_code_grp.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_com_code_grp.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_com_code_grp.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_com_code_grp.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_com_code_grp.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_com_code (
    cd_grp_id varchar(26) NOT NULL,
    cd varchar(20) NOT NULL,
    cd_nm varchar(100) NOT NULL,
    sort_seq integer DEFAULT 0 NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_com_code PRIMARY KEY (cd_grp_id, cd),
    CONSTRAINT ck_tb_com_code_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_com_code IS '업무 공통코드 정보';
COMMENT ON COLUMN tb_com_code.cd_grp_id IS '소속 코드 그룹 식별자';
COMMENT ON COLUMN tb_com_code.cd IS '코드 값';
COMMENT ON COLUMN tb_com_code.cd_nm IS '코드 명칭';
COMMENT ON COLUMN tb_com_code.sort_seq IS '코드 표시 순서';
COMMENT ON COLUMN tb_com_code.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_com_code.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_com_code.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_com_code.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_com_code.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_sys_config (
    sys_config_id varchar(26) NOT NULL,
    sys_config_key varchar(100) NOT NULL,
    sys_config_val text,
    sys_config_desc_cont text,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sys_config PRIMARY KEY (sys_config_id),
    CONSTRAINT ck_tb_sys_config_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sys_config IS '시스템 운영환경 설정';
COMMENT ON COLUMN tb_sys_config.sys_config_id IS '시스템 설정 식별자';
COMMENT ON COLUMN tb_sys_config.sys_config_key IS '시스템 설정 조회 키';
COMMENT ON COLUMN tb_sys_config.sys_config_val IS '시스템 설정 값';
COMMENT ON COLUMN tb_sys_config.sys_config_desc_cont IS '시스템 설정 설명';
COMMENT ON COLUMN tb_sys_config.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_sys_config.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_sys_config.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_sys_config.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_sys_config.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_sys_ext_rel_config (
    ext_rel_config_id varchar(26) NOT NULL,
    ext_sys_cd varchar(20) NOT NULL,
    ext_sys_nm varchar(200) NOT NULL,
    api_base_url varchar(300),
    service_key_ref_nm varchar(100),
    rsp_format_cd varchar(20),
    page_inq_cnt integer,
    max_call_cnt integer,
    conn_timeout_sec integer,
    rsp_timeout_sec integer,
    max_retry_cnt integer,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sys_ext_rel_config PRIMARY KEY (ext_rel_config_id),
    CONSTRAINT ck_tb_sys_ext_rel_config_01 CHECK (del_yn in ('Y','N')),
    CONSTRAINT ck_tb_sys_ext_rel_config_02 CHECK ((page_inq_cnt is null or page_inq_cnt > 0) and (max_call_cnt is null or max_call_cnt > 0) and (conn_timeout_sec is null or conn_timeout_sec > 0) and (rsp_timeout_sec is null or rsp_timeout_sec > 0) and (max_retry_cnt is null or max_retry_cnt >= 0))
);

COMMENT ON TABLE tb_sys_ext_rel_config IS '외부시스템 API 접속 및 호출정책 설정';
COMMENT ON COLUMN tb_sys_ext_rel_config.ext_rel_config_id IS '외부시스템 연계설정 식별자';
COMMENT ON COLUMN tb_sys_ext_rel_config.ext_sys_cd IS '연계 대상 외부시스템 코드';
COMMENT ON COLUMN tb_sys_ext_rel_config.ext_sys_nm IS '연계 대상 외부시스템 명칭';
COMMENT ON COLUMN tb_sys_ext_rel_config.api_base_url IS '외부 API 기본 URL';
COMMENT ON COLUMN tb_sys_ext_rel_config.service_key_ref_nm IS '환경변수 또는 보안 저장소의 서비스키 참조명';
COMMENT ON COLUMN tb_sys_ext_rel_config.rsp_format_cd IS '외부 API 응답 형식 코드';
COMMENT ON COLUMN tb_sys_ext_rel_config.page_inq_cnt IS '페이지당 기본 조회 건수';
COMMENT ON COLUMN tb_sys_ext_rel_config.max_call_cnt IS '수집 실행당 최대 API 호출 건수';
COMMENT ON COLUMN tb_sys_ext_rel_config.conn_timeout_sec IS '외부 API 연결 타임아웃 초';
COMMENT ON COLUMN tb_sys_ext_rel_config.rsp_timeout_sec IS '외부 API 응답 타임아웃 초';
COMMENT ON COLUMN tb_sys_ext_rel_config.max_retry_cnt IS '실패 시 최대 재시도 건수';
COMMENT ON COLUMN tb_sys_ext_rel_config.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_sys_ext_rel_config.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_sys_ext_rel_config.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_sys_ext_rel_config.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_sys_ext_rel_config.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_sys_api_call_log (
    api_call_log_id varchar(26) NOT NULL,
    ext_rel_config_id varchar(26) NOT NULL,
    collect_hist_id varchar(26) NOT NULL,
    call_start_dtm timestamp,
    call_end_dtm timestamp,
    req_url varchar(300),
    req_cond_cont text,
    http_status_cd varchar(20),
    api_result_cd varchar(20),
    rsp_cnt integer DEFAULT 0,
    api_call_result_cd varchar(20),
    err_cont text,
    reproc_status_cd varchar(20),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    CONSTRAINT pk_tb_sys_api_call_log PRIMARY KEY (api_call_log_id),
    CONSTRAINT ck_tb_sys_api_call_log_01 CHECK (rsp_cnt is null or rsp_cnt >= 0),
    CONSTRAINT ck_tb_sys_api_call_log_02 CHECK (call_end_dtm is null or call_start_dtm is null or call_end_dtm >= call_start_dtm)
);

COMMENT ON TABLE tb_sys_api_call_log IS '외부 API 호출 요청과 응답 및 오류 결과';
COMMENT ON COLUMN tb_sys_api_call_log.api_call_log_id IS 'API 호출 로그 식별자';
COMMENT ON COLUMN tb_sys_api_call_log.ext_rel_config_id IS '호출에 사용한 외부시스템 연계설정 식별자';
COMMENT ON COLUMN tb_sys_api_call_log.collect_hist_id IS '호출이 속한 사업공고 수집 실행 식별자';
COMMENT ON COLUMN tb_sys_api_call_log.call_start_dtm IS '외부 API 호출 시작 일시';
COMMENT ON COLUMN tb_sys_api_call_log.call_end_dtm IS '외부 API 호출 종료 일시';
COMMENT ON COLUMN tb_sys_api_call_log.req_url IS '민감한 쿼리값을 제거하거나 마스킹한 요청 URL';
COMMENT ON COLUMN tb_sys_api_call_log.req_cond_cont IS '민감값을 마스킹한 요청 조건';
COMMENT ON COLUMN tb_sys_api_call_log.http_status_cd IS '외부 API HTTP 응답 상태 코드';
COMMENT ON COLUMN tb_sys_api_call_log.api_result_cd IS '외부 API가 반환한 결과 코드';
COMMENT ON COLUMN tb_sys_api_call_log.rsp_cnt IS '외부 API 응답 데이터 건수';
COMMENT ON COLUMN tb_sys_api_call_log.api_call_result_cd IS 'API 호출 처리 결과 코드';
COMMENT ON COLUMN tb_sys_api_call_log.err_cont IS 'API 호출 또는 응답 처리 오류 내용';
COMMENT ON COLUMN tb_sys_api_call_log.reproc_status_cd IS '실패 호출의 재처리 상태 코드';
COMMENT ON COLUMN tb_sys_api_call_log.reg_id IS '로그 생성 주체';
COMMENT ON COLUMN tb_sys_api_call_log.reg_dtm IS '로그 저장 일시';

CREATE TABLE tb_sys_access_log (
    access_log_id varchar(26) NOT NULL,
    user_id varchar(26),
    access_dtm timestamp DEFAULT current_timestamp NOT NULL,
    logout_dtm timestamp,
    access_ip_addr varchar(45),
    succ_yn char(1) DEFAULT 'N' NOT NULL,
    reg_id varchar(26) DEFAULT 'SYSTEM' NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    fail_rsn_cd varchar(20),
    logout_type_cd varchar(20),
    req_trace_id varchar(64) NOT NULL,
    login_id_hash_val varchar(255),
    user_agent_cont text,
    CONSTRAINT pk_tb_sys_access_log PRIMARY KEY (access_log_id),
    CONSTRAINT ck_tb_sys_access_log_01 CHECK (succ_yn in ('Y','N')),
    CONSTRAINT ck_tb_sys_access_log_02 CHECK ((succ_yn = 'Y' and fail_rsn_cd is null) or (succ_yn = 'N' and fail_rsn_cd is not null)),
    CONSTRAINT ck_tb_sys_access_log_03 CHECK ((logout_dtm is null and logout_type_cd is null) or (succ_yn = 'Y' and logout_dtm is not null and logout_type_cd is not null))
);

COMMENT ON TABLE tb_sys_access_log IS '로그인 및 접속 이력';
COMMENT ON COLUMN tb_sys_access_log.access_log_id IS '접속 로그 식별자';
COMMENT ON COLUMN tb_sys_access_log.user_id IS '접속 사용자 식별자';
COMMENT ON COLUMN tb_sys_access_log.access_dtm IS '접속 발생 일시';
COMMENT ON COLUMN tb_sys_access_log.logout_dtm IS '정상 로그아웃 또는 세션 종료 일시';
COMMENT ON COLUMN tb_sys_access_log.access_ip_addr IS '접속 원본 IP 주소';
COMMENT ON COLUMN tb_sys_access_log.succ_yn IS '접속 성공 여부';
COMMENT ON COLUMN tb_sys_access_log.reg_id IS '로그 생성 주체';
COMMENT ON COLUMN tb_sys_access_log.reg_dtm IS '로그 저장 일시';
COMMENT ON COLUMN tb_sys_access_log.fail_rsn_cd IS '로그인 실패 사유 내부 코드';
COMMENT ON COLUMN tb_sys_access_log.logout_type_cd IS '세션 종료 유형 코드';
COMMENT ON COLUMN tb_sys_access_log.req_trace_id IS '로그인 요청과 서버 로그 연결 식별자';
COMMENT ON COLUMN tb_sys_access_log.login_id_hash_val IS '미등록 로그인ID 추적용 단방향 해시값';
COMMENT ON COLUMN tb_sys_access_log.user_agent_cont IS '접속 브라우저 및 클라이언트 식별정보';

CREATE TABLE tb_sys_log (
    log_id varchar(26) NOT NULL,
    log_type_cd varchar(20) NOT NULL,
    proc_user_id varchar(26),
    occur_dtm timestamp DEFAULT current_timestamp NOT NULL,
    log_cont text,
    reg_id varchar(26) DEFAULT 'SYSTEM' NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    event_type_cd varchar(50) NOT NULL,
    tgt_type_cd varchar(20),
    tgt_id varchar(26),
    proc_result_cd varchar(20) NOT NULL,
    chg_smry_cont text,
    req_trace_id varchar(64),
    access_ip_addr varchar(45),
    CONSTRAINT pk_tb_sys_log PRIMARY KEY (log_id),
    CONSTRAINT ck_tb_sys_log_01 CHECK (proc_result_cd in ('SUCCESS','FAILURE')),
    CONSTRAINT ck_tb_sys_log_02 CHECK ((tgt_type_cd is null and tgt_id is null) or (tgt_type_cd is not null and tgt_id is not null))
);

COMMENT ON TABLE tb_sys_log IS '시스템 사용 및 오류 로그';
COMMENT ON COLUMN tb_sys_log.log_id IS '시스템 로그 식별자';
COMMENT ON COLUMN tb_sys_log.log_type_cd IS '로그 유형 코드';
COMMENT ON COLUMN tb_sys_log.proc_user_id IS '업무 처리를 수행한 사용자 식별자';
COMMENT ON COLUMN tb_sys_log.occur_dtm IS '로그 사건 발생 일시';
COMMENT ON COLUMN tb_sys_log.log_cont IS '로그 상세 내용';
COMMENT ON COLUMN tb_sys_log.reg_id IS '로그 생성 주체';
COMMENT ON COLUMN tb_sys_log.reg_dtm IS '로그 저장 일시';
COMMENT ON COLUMN tb_sys_log.event_type_cd IS '구체적인 업무 사건 코드';
COMMENT ON COLUMN tb_sys_log.tgt_type_cd IS '처리 대상 유형 코드';
COMMENT ON COLUMN tb_sys_log.tgt_id IS '변경된 사용자 또는 역할 식별자';
COMMENT ON COLUMN tb_sys_log.proc_result_cd IS '업무 처리 결과 코드';
COMMENT ON COLUMN tb_sys_log.chg_smry_cont IS '개인정보를 제외한 변경 항목 요약';
COMMENT ON COLUMN tb_sys_log.req_trace_id IS 'API 요청과 서버 로그 연결 식별자';
COMMENT ON COLUMN tb_sys_log.access_ip_addr IS '처리 요청 원본 IP 주소';

CREATE TABLE tb_sys_notice (
    notice_id varchar(26) NOT NULL,
    title varchar(200) NOT NULL,
    cont text,
    post_start_dt date NOT NULL,
    post_end_dt date,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sys_notice PRIMARY KEY (notice_id),
    CONSTRAINT ck_tb_sys_notice_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sys_notice IS '시스템 공지사항';
COMMENT ON COLUMN tb_sys_notice.notice_id IS '공지사항 식별자';
COMMENT ON COLUMN tb_sys_notice.title IS '공지사항 제목';
COMMENT ON COLUMN tb_sys_notice.cont IS '공지사항 본문 내용';
COMMENT ON COLUMN tb_sys_notice.post_start_dt IS '게시 시작 일자';
COMMENT ON COLUMN tb_sys_notice.post_end_dt IS '게시 종료 일자';
COMMENT ON COLUMN tb_sys_notice.reg_id IS '공지사항 등록자 식별자';
COMMENT ON COLUMN tb_sys_notice.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_sys_notice.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_sys_notice.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_sys_notice.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_com_noti (
    noti_id varchar(26) NOT NULL,
    rcvr_id varchar(26) NOT NULL,
    noti_type_cd varchar(20) NOT NULL,
    title varchar(200) NOT NULL,
    cont text,
    read_yn char(1) DEFAULT 'N' NOT NULL,
    occur_dtm timestamp DEFAULT current_timestamp NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_com_noti PRIMARY KEY (noti_id),
    CONSTRAINT ck_tb_com_noti_01 CHECK (read_yn in ('Y','N')),
    CONSTRAINT ck_tb_com_noti_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_com_noti IS '사용자별 업무 진행상태 및 주요 이벤트 알림';
COMMENT ON COLUMN tb_com_noti.noti_id IS '알림 식별자';
COMMENT ON COLUMN tb_com_noti.rcvr_id IS '알림 수신 사용자 식별자';
COMMENT ON COLUMN tb_com_noti.noti_type_cd IS '알림 유형 코드';
COMMENT ON COLUMN tb_com_noti.title IS '알림 제목';
COMMENT ON COLUMN tb_com_noti.cont IS '알림 상세 내용';
COMMENT ON COLUMN tb_com_noti.read_yn IS '수신자의 알림 읽음 여부';
COMMENT ON COLUMN tb_com_noti.occur_dtm IS '알림 발생 일시';
COMMENT ON COLUMN tb_com_noti.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_com_noti.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_com_noti.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_com_noti.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_com_noti.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_com_task_tgt (
    task_tgt_id varchar(26) NOT NULL,
    task_tgt_type_cd varchar(20) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_com_task_tgt PRIMARY KEY (task_tgt_id),
    CONSTRAINT ck_tb_com_task_tgt_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_com_task_tgt IS '첨부파일과 메모 등 공통 기능이 연결되는 업무 엔터티의 공통 식별정보';
COMMENT ON COLUMN tb_com_task_tgt.task_tgt_id IS '공통 기능이 연결되는 업무대상 식별자';
COMMENT ON COLUMN tb_com_task_tgt.task_tgt_type_cd IS '구체적인 업무 엔터티의 유형 코드';
COMMENT ON COLUMN tb_com_task_tgt.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_com_task_tgt.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_com_task_tgt.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_com_task_tgt.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_com_task_tgt.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_com_file (
    file_id varchar(26) NOT NULL,
    task_tgt_id varchar(26) NOT NULL,
    orgnl_file_nm varchar(200) NOT NULL,
    save_file_nm varchar(200) NOT NULL,
    file_path varchar(1000) NOT NULL,
    file_size bigint NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_com_file PRIMARY KEY (file_id),
    CONSTRAINT ck_tb_com_file_01 CHECK (file_size >= 0),
    CONSTRAINT ck_tb_com_file_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_com_file IS '업무대상별 첨부파일 메타정보';
COMMENT ON COLUMN tb_com_file.file_id IS '첨부파일 식별자';
COMMENT ON COLUMN tb_com_file.task_tgt_id IS '첨부파일이 소속되는 업무대상 식별자';
COMMENT ON COLUMN tb_com_file.orgnl_file_nm IS '사용자가 업로드한 원본 파일명';
COMMENT ON COLUMN tb_com_file.save_file_nm IS '파일 저장소에서 사용하는 시스템 생성 파일명';
COMMENT ON COLUMN tb_com_file.file_path IS '파일 저장소 내 정규화된 경로 또는 객체 키';
COMMENT ON COLUMN tb_com_file.file_size IS '파일의 바이트 단위 크기';
COMMENT ON COLUMN tb_com_file.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_com_file.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_com_file.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_com_file.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_com_file.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_com_memo (
    memo_id varchar(26) NOT NULL,
    task_tgt_id varchar(26) NOT NULL,
    cont text NOT NULL,
    wrtr_id varchar(26) NOT NULL,
    wrt_dtm timestamp DEFAULT current_timestamp NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_com_memo PRIMARY KEY (memo_id),
    CONSTRAINT ck_tb_com_memo_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_com_memo IS '업무대상별 메모 및 의견';
COMMENT ON COLUMN tb_com_memo.memo_id IS '메모 식별자';
COMMENT ON COLUMN tb_com_memo.task_tgt_id IS '메모가 소속되는 업무대상 식별자';
COMMENT ON COLUMN tb_com_memo.cont IS '메모 내용';
COMMENT ON COLUMN tb_com_memo.wrtr_id IS '메모 작성 사용자 식별자';
COMMENT ON COLUMN tb_com_memo.wrt_dtm IS '메모 작성 일시';
COMMENT ON COLUMN tb_com_memo.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_com_memo.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_com_memo.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_com_memo.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_com_memo.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_cust_mst (
    cust_id varchar(26) NOT NULL,
    cust_nm varchar(200) NOT NULL,
    cust_type_cd varchar(20) NOT NULL,
    biz_reg_no varchar(20),
    ceo_nm varchar(100),
    tel_no varchar(20),
    email_addr varchar(100),
    addr varchar(500),
    cust_status_cd varchar(20) DEFAULT 'ACTIVE' NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_cust_mst PRIMARY KEY (cust_id),
    CONSTRAINT ck_tb_cust_mst_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_cust_mst IS '고객사 기본정보 및 업무 상태';
COMMENT ON COLUMN tb_cust_mst.cust_id IS '고객사 식별자';
COMMENT ON COLUMN tb_cust_mst.cust_nm IS '고객사 명칭';
COMMENT ON COLUMN tb_cust_mst.cust_type_cd IS '고객 유형 코드';
COMMENT ON COLUMN tb_cust_mst.biz_reg_no IS '고객사의 사업자등록번호';
COMMENT ON COLUMN tb_cust_mst.ceo_nm IS '고객사 대표자 명칭';
COMMENT ON COLUMN tb_cust_mst.tel_no IS '고객사 대표 전화번호';
COMMENT ON COLUMN tb_cust_mst.email_addr IS '고객사 대표 이메일 주소';
COMMENT ON COLUMN tb_cust_mst.addr IS '고객사 주소';
COMMENT ON COLUMN tb_cust_mst.cust_status_cd IS '고객사의 업무 상태 코드';
COMMENT ON COLUMN tb_cust_mst.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_cust_mst.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_cust_mst.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_cust_mst.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_cust_mst.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_cust_contact (
    cust_contact_id varchar(26) NOT NULL,
    cust_id varchar(26) NOT NULL,
    cust_contact_nm varchar(100) NOT NULL,
    dept_nm varchar(100),
    job_pos_nm varchar(100),
    email_addr varchar(100),
    tel_no varchar(20),
    mobile_no varchar(20),
    cust_contact_status_cd varchar(20) DEFAULT 'ACTIVE' NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_cust_contact PRIMARY KEY (cust_contact_id),
    CONSTRAINT ck_tb_cust_contact_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_cust_contact IS '고객사 소속 담당자 기본정보 및 상태';
COMMENT ON COLUMN tb_cust_contact.cust_contact_id IS '고객담당자 식별자';
COMMENT ON COLUMN tb_cust_contact.cust_id IS '소속 고객사 식별자';
COMMENT ON COLUMN tb_cust_contact.cust_contact_nm IS '고객담당자 명칭';
COMMENT ON COLUMN tb_cust_contact.dept_nm IS '고객담당자 소속 부서 명칭';
COMMENT ON COLUMN tb_cust_contact.job_pos_nm IS '고객담당자 직위 명칭';
COMMENT ON COLUMN tb_cust_contact.email_addr IS '고객담당자 이메일 주소';
COMMENT ON COLUMN tb_cust_contact.tel_no IS '고객담당자 유선 전화번호';
COMMENT ON COLUMN tb_cust_contact.mobile_no IS '고객담당자 휴대전화 번호';
COMMENT ON COLUMN tb_cust_contact.cust_contact_status_cd IS '고객담당자의 활성 또는 비활성 상태 코드';
COMMENT ON COLUMN tb_cust_contact.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_cust_contact.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_cust_contact.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_cust_contact.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_cust_contact.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_cust_activity (
    act_id varchar(26) NOT NULL,
    cust_id varchar(26) NOT NULL,
    cust_contact_id varchar(26),
    act_type_cd varchar(20) NOT NULL,
    act_dtm timestamp NOT NULL,
    act_cont text,
    act_chrg_user_id varchar(26) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_cust_activity PRIMARY KEY (act_id),
    CONSTRAINT ck_tb_cust_activity_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_cust_activity IS '고객 대상 방문 전화 메일 미팅 등 영업활동 이력';
COMMENT ON COLUMN tb_cust_activity.act_id IS '영업활동 식별자';
COMMENT ON COLUMN tb_cust_activity.cust_id IS '영업활동 대상 고객사 식별자';
COMMENT ON COLUMN tb_cust_activity.cust_contact_id IS '영업활동 대상 고객담당자 식별자';
COMMENT ON COLUMN tb_cust_activity.act_type_cd IS '방문 전화 메일 미팅 등 활동 유형 코드';
COMMENT ON COLUMN tb_cust_activity.act_dtm IS '영업활동 수행 일시';
COMMENT ON COLUMN tb_cust_activity.act_cont IS '영업활동 상세 내용';
COMMENT ON COLUMN tb_cust_activity.act_chrg_user_id IS '영업활동 담당 BMS 사용자 식별자';
COMMENT ON COLUMN tb_cust_activity.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_cust_activity.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_cust_activity.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_cust_activity.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_cust_activity.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_sales_annc (
    annc_id varchar(26) NOT NULL,
    annc_nm varchar(200) NOT NULL,
    demand_inst_cd varchar(20),
    bid_start_dtm timestamp,
    bid_end_dtm timestamp,
    bid_open_dtm timestamp,
    close_dt date,
    budget_amt numeric(15,2),
    annc_status_cd varchar(20),
    annc_type_cd varchar(20),
    bid_annc_no varchar(30),
    demand_inst_nm varchar(200) NOT NULL,
    bid_mthd_nm varchar(100),
    cntr_mthd_nm varchar(100),
    cntr_se_nm varchar(100),
    rebid_yn char(1) DEFAULT 'N' NOT NULL,
    emrg_annc_yn char(1) DEFAULT 'N' NOT NULL,
    order_inst_contact_position varchar(100),
    order_inst_contact_nm varchar(100),
    order_inst_contact_tel_no varchar(20),
    bid_annc_ord integer,
    annc_src_se_cd varchar(20) NOT NULL,
    annc_review_status_cd varchar(20) DEFAULT 'UNREVIEWED' NOT NULL,
    review_contact_id varchar(26),
    review_dtm timestamp,
    contact_opinion_cont text,
    user_suppl_info_cont text,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    orgnl_annc_id varchar(26),
    bid_prgrs_status_cd varchar(20) NOT NULL,
    bid_result_cd varchar(20),
    result_cnfm_dtm timestamp,
    result_cnfm_mthd_cd varchar(20),
    task_tgt_id varchar(26) NOT NULL,
    CONSTRAINT pk_tb_sales_annc PRIMARY KEY (annc_id),
    CONSTRAINT ck_tb_sales_annc_01 CHECK (rebid_yn in ('Y','N')),
    CONSTRAINT ck_tb_sales_annc_02 CHECK (emrg_annc_yn in ('Y','N')),
    CONSTRAINT ck_tb_sales_annc_03 CHECK (del_yn in ('Y','N')),
    CONSTRAINT ck_tb_sales_annc_04 CHECK (budget_amt is null or budget_amt >= 0),
    CONSTRAINT ck_tb_sales_annc_05 CHECK (bid_end_dtm is null or bid_start_dtm is null or bid_end_dtm >= bid_start_dtm),
    CONSTRAINT ck_tb_sales_annc_06 CHECK (bid_open_dtm is null or bid_end_dtm is null or bid_open_dtm >= bid_end_dtm),
    CONSTRAINT ck_tb_sales_annc_07 CHECK ((bid_annc_no is null and bid_annc_ord is null) or (bid_annc_no is not null and bid_annc_ord is not null and bid_annc_ord >= 0)),
    CONSTRAINT ck_tb_sales_annc_08 CHECK (orgnl_annc_id is null or orgnl_annc_id <> annc_id),
    CONSTRAINT ck_tb_sales_annc_09 CHECK ((review_contact_id is null and review_dtm is null) or (review_contact_id is not null and review_dtm is not null)),
    CONSTRAINT ck_tb_sales_annc_10 CHECK ((bid_result_cd is null and result_cnfm_dtm is null and result_cnfm_mthd_cd is null) or (bid_result_cd is not null and result_cnfm_dtm is not null and result_cnfm_mthd_cd is not null))
);

COMMENT ON TABLE tb_sales_annc IS '수동 등록 및 외부 자동수집 사업공고 통합정보';
COMMENT ON COLUMN tb_sales_annc.annc_id IS '사업공고의 공고ID';
COMMENT ON COLUMN tb_sales_annc.annc_nm IS '사업공고의 공고명';
COMMENT ON COLUMN tb_sales_annc.demand_inst_cd IS '사업공고의 수요기관코드';
COMMENT ON COLUMN tb_sales_annc.bid_start_dtm IS '사업공고의 입찰개시일시';
COMMENT ON COLUMN tb_sales_annc.bid_end_dtm IS '사업공고의 입찰마감일시';
COMMENT ON COLUMN tb_sales_annc.bid_open_dtm IS '사업공고의 개찰일시';
COMMENT ON COLUMN tb_sales_annc.close_dt IS '사업공고의 마감일';
COMMENT ON COLUMN tb_sales_annc.budget_amt IS '사업공고의 예산금액';
COMMENT ON COLUMN tb_sales_annc.annc_status_cd IS '사업공고의 공고상태';
COMMENT ON COLUMN tb_sales_annc.annc_type_cd IS '사업공고의 공고종류코드';
COMMENT ON COLUMN tb_sales_annc.bid_annc_no IS '사업공고의 입찰공고번호';
COMMENT ON COLUMN tb_sales_annc.demand_inst_nm IS '사업공고의 수요기관명';
COMMENT ON COLUMN tb_sales_annc.bid_mthd_nm IS '사업공고의 입찰방식';
COMMENT ON COLUMN tb_sales_annc.cntr_mthd_nm IS '사업공고의 계약방법';
COMMENT ON COLUMN tb_sales_annc.cntr_se_nm IS '사업공고의 계약구분';
COMMENT ON COLUMN tb_sales_annc.rebid_yn IS '사업공고의 재입찰여부';
COMMENT ON COLUMN tb_sales_annc.emrg_annc_yn IS '사업공고의 긴급공고여부';
COMMENT ON COLUMN tb_sales_annc.order_inst_contact_position IS '사업공고의 발주기관담당자직급';
COMMENT ON COLUMN tb_sales_annc.order_inst_contact_nm IS '사업공고의 발주기관담당자명';
COMMENT ON COLUMN tb_sales_annc.order_inst_contact_tel_no IS '사업공고의 발주기관담당자연락처';
COMMENT ON COLUMN tb_sales_annc.bid_annc_ord IS '사업공고의 입찰공고차수';
COMMENT ON COLUMN tb_sales_annc.annc_src_se_cd IS '사업공고가 유입된 출처의 구분 코드';
COMMENT ON COLUMN tb_sales_annc.annc_review_status_cd IS '사업공고의 공고검토상태코드';
COMMENT ON COLUMN tb_sales_annc.review_contact_id IS '사업공고 검토 담당 사용자 식별자';
COMMENT ON COLUMN tb_sales_annc.review_dtm IS '사업공고를 검토한 일시';
COMMENT ON COLUMN tb_sales_annc.contact_opinion_cont IS '사업공고 검토 담당자의 의견 내용';
COMMENT ON COLUMN tb_sales_annc.user_suppl_info_cont IS '사용자가 사업공고에 추가하거나 보정한 정보 내용';
COMMENT ON COLUMN tb_sales_annc.reg_id IS '사업공고의 등록자ID';
COMMENT ON COLUMN tb_sales_annc.reg_dtm IS '사업공고의 등록일시';
COMMENT ON COLUMN tb_sales_annc.mod_id IS '사업공고의 수정자ID';
COMMENT ON COLUMN tb_sales_annc.mod_dtm IS '사업공고의 수정일시';
COMMENT ON COLUMN tb_sales_annc.del_yn IS '사업공고의 삭제여부';
COMMENT ON COLUMN tb_sales_annc.orgnl_annc_id IS '재공고가 참조하는 최초 사업공고 식별자';
COMMENT ON COLUMN tb_sales_annc.bid_prgrs_status_cd IS '공고부터 최종 결과까지의 입찰 진행단계 코드';
COMMENT ON COLUMN tb_sales_annc.bid_result_cd IS '단독입찰 유찰 낙찰 등 입찰 결과 코드';
COMMENT ON COLUMN tb_sales_annc.result_cnfm_dtm IS '입찰 결과를 확인한 일시';
COMMENT ON COLUMN tb_sales_annc.result_cnfm_mthd_cd IS 'API 또는 수동확인 등 결과 확인방법 코드';
COMMENT ON COLUMN tb_sales_annc.task_tgt_id IS '사업공고의 공통 기능 연결 업무대상 식별자';

CREATE TABLE tb_sales_annc_collect_cond (
    collect_cond_id varchar(26) NOT NULL,
    collect_cond_nm varchar(200) NOT NULL,
    annc_biz_se_cd varchar(20) NOT NULL,
    collect_tgt_start_dt date,
    collect_tgt_end_dt date,
    last_succ_collect_dtm timestamp,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sales_annc_collect_cond PRIMARY KEY (collect_cond_id),
    CONSTRAINT ck_tb_sales_annc_collect_cond_01 CHECK (collect_tgt_end_dt is null or collect_tgt_start_dt is null or collect_tgt_end_dt >= collect_tgt_start_dt),
    CONSTRAINT ck_tb_sales_annc_collect_cond_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sales_annc_collect_cond IS '발주기관 키워드 및 업무구분별 사업공고 자동수집 조건';
COMMENT ON COLUMN tb_sales_annc_collect_cond.collect_cond_id IS '사업공고수집조건의 수집조건ID';
COMMENT ON COLUMN tb_sales_annc_collect_cond.collect_cond_nm IS '사업공고수집조건의 수집조건명';
COMMENT ON COLUMN tb_sales_annc_collect_cond.annc_biz_se_cd IS '사업공고수집조건의 공고업무구분코드';
COMMENT ON COLUMN tb_sales_annc_collect_cond.collect_tgt_start_dt IS '사업공고수집조건의 수집대상시작일자';
COMMENT ON COLUMN tb_sales_annc_collect_cond.collect_tgt_end_dt IS '사업공고수집조건의 수집대상종료일자';
COMMENT ON COLUMN tb_sales_annc_collect_cond.last_succ_collect_dtm IS '사업공고수집조건의 마지막성공수집일시';
COMMENT ON COLUMN tb_sales_annc_collect_cond.reg_id IS '사업공고수집조건의 등록자ID';
COMMENT ON COLUMN tb_sales_annc_collect_cond.reg_dtm IS '사업공고수집조건의 등록일시';
COMMENT ON COLUMN tb_sales_annc_collect_cond.mod_id IS '사업공고수집조건의 수정자ID';
COMMENT ON COLUMN tb_sales_annc_collect_cond.mod_dtm IS '사업공고수집조건의 수정일시';
COMMENT ON COLUMN tb_sales_annc_collect_cond.del_yn IS '사업공고수집조건의 삭제여부';

CREATE TABLE tb_sales_annc_collect_tgt_inst (
    collect_tgt_inst_id varchar(26) NOT NULL,
    collect_cond_id varchar(26) NOT NULL,
    order_inst_cd varchar(20) NOT NULL,
    order_inst_nm varchar(200),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sales_annc_collect_tgt_inst PRIMARY KEY (collect_tgt_inst_id),
    CONSTRAINT ck_tb_sales_annc_collect_tgt_inst_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sales_annc_collect_tgt_inst IS '수집조건별 대상 발주기관';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.collect_tgt_inst_id IS '사업공고수집대상기관의 수집대상기관ID';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.collect_cond_id IS '사업공고수집대상기관의 수집조건ID';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.order_inst_cd IS '사업공고수집대상기관의 발주기관코드';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.order_inst_nm IS '사업공고수집대상기관의 발주기관명';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.reg_id IS '사업공고수집대상기관의 등록자ID';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.reg_dtm IS '사업공고수집대상기관의 등록일시';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.mod_id IS '사업공고수집대상기관의 수정자ID';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.mod_dtm IS '사업공고수집대상기관의 수정일시';
COMMENT ON COLUMN tb_sales_annc_collect_tgt_inst.del_yn IS '사업공고수집대상기관의 삭제여부';

CREATE TABLE tb_sales_annc_collect_kwd (
    collect_kwd_id varchar(26) NOT NULL,
    collect_cond_id varchar(26) NOT NULL,
    kwd_se_cd varchar(20) NOT NULL,
    kwd_cont varchar(200) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sales_annc_collect_kwd PRIMARY KEY (collect_kwd_id),
    CONSTRAINT ck_tb_sales_annc_collect_kwd_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sales_annc_collect_kwd IS '수집조건별 포함 및 제외 키워드';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.collect_kwd_id IS '사업공고수집키워드의 수집키워드ID';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.collect_cond_id IS '사업공고수집키워드의 수집조건ID';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.kwd_se_cd IS '사업공고수집키워드의 키워드구분코드';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.kwd_cont IS '사업공고수집키워드의 키워드내용';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.reg_id IS '사업공고수집키워드의 등록자ID';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.reg_dtm IS '사업공고수집키워드의 등록일시';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.mod_id IS '사업공고수집키워드의 수정자ID';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.mod_dtm IS '사업공고수집키워드의 수정일시';
COMMENT ON COLUMN tb_sales_annc_collect_kwd.del_yn IS '사업공고수집키워드의 삭제여부';

CREATE TABLE tb_sales_annc_collect_hist (
    collect_hist_id varchar(26) NOT NULL,
    collect_cond_id varchar(26) NOT NULL,
    collect_exec_type_cd varchar(20) NOT NULL,
    collect_start_dtm timestamp NOT NULL,
    collect_end_dtm timestamp,
    inq_start_dtm timestamp,
    inq_end_dtm timestamp,
    rsp_cnt integer DEFAULT 0 NOT NULL,
    new_cnt integer DEFAULT 0 NOT NULL,
    chg_cnt integer DEFAULT 0 NOT NULL,
    dup_cnt integer DEFAULT 0 NOT NULL,
    err_cnt integer DEFAULT 0 NOT NULL,
    collect_proc_status_cd varchar(20) NOT NULL,
    err_cont text,
    reproc_status_cd varchar(20),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    CONSTRAINT pk_tb_sales_annc_collect_hist PRIMARY KEY (collect_hist_id),
    CONSTRAINT ck_tb_sales_annc_collect_hist_01 CHECK (rsp_cnt >= 0 and new_cnt >= 0 and chg_cnt >= 0 and dup_cnt >= 0 and err_cnt >= 0),
    CONSTRAINT ck_tb_sales_annc_collect_hist_02 CHECK (collect_end_dtm is null or collect_end_dtm >= collect_start_dtm),
    CONSTRAINT ck_tb_sales_annc_collect_hist_03 CHECK (inq_end_dtm is null or inq_start_dtm is null or inq_end_dtm >= inq_start_dtm)
);

COMMENT ON TABLE tb_sales_annc_collect_hist IS '사업공고 수집 실행 단위 처리 결과와 재처리 상태';
COMMENT ON COLUMN tb_sales_annc_collect_hist.collect_hist_id IS '사업공고수집이력의 수집이력ID';
COMMENT ON COLUMN tb_sales_annc_collect_hist.collect_cond_id IS '사업공고수집이력의 수집조건ID';
COMMENT ON COLUMN tb_sales_annc_collect_hist.collect_exec_type_cd IS '사업공고수집이력의 수집실행유형코드';
COMMENT ON COLUMN tb_sales_annc_collect_hist.collect_start_dtm IS '사업공고수집이력의 수집시작일시';
COMMENT ON COLUMN tb_sales_annc_collect_hist.collect_end_dtm IS '사업공고수집이력의 수집종료일시';
COMMENT ON COLUMN tb_sales_annc_collect_hist.inq_start_dtm IS '사업공고수집이력의 조회시작일시';
COMMENT ON COLUMN tb_sales_annc_collect_hist.inq_end_dtm IS '사업공고수집이력의 조회종료일시';
COMMENT ON COLUMN tb_sales_annc_collect_hist.rsp_cnt IS '사업공고수집이력의 응답건수';
COMMENT ON COLUMN tb_sales_annc_collect_hist.new_cnt IS '사업공고수집이력의 신규건수';
COMMENT ON COLUMN tb_sales_annc_collect_hist.chg_cnt IS '사업공고수집이력의 변경건수';
COMMENT ON COLUMN tb_sales_annc_collect_hist.dup_cnt IS '사업공고수집이력의 중복건수';
COMMENT ON COLUMN tb_sales_annc_collect_hist.err_cnt IS '사업공고수집이력의 오류건수';
COMMENT ON COLUMN tb_sales_annc_collect_hist.collect_proc_status_cd IS '사업공고수집이력의 수집처리상태코드';
COMMENT ON COLUMN tb_sales_annc_collect_hist.err_cont IS '사업공고수집이력의 오류내용';
COMMENT ON COLUMN tb_sales_annc_collect_hist.reproc_status_cd IS '사업공고수집이력의 재처리상태코드';
COMMENT ON COLUMN tb_sales_annc_collect_hist.reg_id IS '사업공고수집이력의 등록자ID';
COMMENT ON COLUMN tb_sales_annc_collect_hist.reg_dtm IS '사업공고수집이력의 등록일시';

CREATE TABLE tb_sales_annc_collect_orgnl (
    collect_orgnl_id varchar(26) NOT NULL,
    collect_hist_id varchar(26) NOT NULL,
    bid_annc_no varchar(30) NOT NULL,
    bid_annc_ord integer NOT NULL,
    orgnl_rsp_cont text NOT NULL,
    orgnl_hash_val varchar(255) NOT NULL,
    collect_dtm timestamp DEFAULT current_timestamp NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    CONSTRAINT pk_tb_sales_annc_collect_orgnl PRIMARY KEY (collect_orgnl_id)
);

COMMENT ON TABLE tb_sales_annc_collect_orgnl IS '외부 API 응답 원문과 해시';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.collect_orgnl_id IS '사업공고수집원문의 수집원문ID';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.collect_hist_id IS '사업공고수집원문의 수집이력ID';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.bid_annc_no IS '사업공고수집원문의 입찰공고번호';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.bid_annc_ord IS '사업공고수집원문의 입찰공고차수';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.orgnl_rsp_cont IS '사업공고수집원문의 원문응답내용';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.orgnl_hash_val IS '사업공고수집원문의 원문해시값';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.collect_dtm IS '사업공고수집원문의 수집일시';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.reg_id IS '사업공고수집원문의 등록자ID';
COMMENT ON COLUMN tb_sales_annc_collect_orgnl.reg_dtm IS '사업공고수집원문의 등록일시';

CREATE TABLE tb_sales_annc_rel_rcv (
    rel_rcv_id varchar(26) NOT NULL,
    collect_orgnl_id varchar(26) NOT NULL,
    annc_id varchar(26),
    rel_proc_se_cd varchar(20) NOT NULL,
    rel_proc_status_cd varchar(20) NOT NULL,
    biz_annc_reflect_dtm timestamp,
    reproc_cnt integer DEFAULT 0 NOT NULL,
    err_cont text,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    resultcode text,
    resultmsg text,
    numofrows text,
    pageno text,
    totalcount text,
    bidntceno text,
    bidntceord text,
    rentceyn text,
    rgsttynm text,
    ntcekindnm text,
    intrbidyn text,
    bidntcedt text,
    refno text,
    bidntcenm text,
    ntceinsttcd text,
    ntceinsttnm text,
    dminsttcd text,
    dminsttnm text,
    bidmethdnm text,
    cntrctcnclsmthdnm text,
    ntceinsttofclnm text,
    ntceinsttofcltelno text,
    ntceinsttofclemailadrs text,
    exctvnm text,
    bidqlfctrgstdt text,
    cmmnspldmdagrmntrcptdocmethd text,
    cmmnspldmdagrmntclsedt text,
    cmmnspldmdcorprgnlmtyn text,
    bidbegindt text,
    bidclsedt text,
    opengdt text,
    ntcespecdocurl1 text,
    ntcespecdocurl2 text,
    ntcespecdocurl3 text,
    ntcespecdocurl4 text,
    ntcespecdocurl5 text,
    ntcespecdocurl6 text,
    ntcespecdocurl7 text,
    ntcespecdocurl8 text,
    ntcespecdocurl9 text,
    ntcespecdocurl10 text,
    ntcespecfilenm1 text,
    ntcespecfilenm2 text,
    ntcespecfilenm3 text,
    ntcespecfilenm4 text,
    ntcespecfilenm5 text,
    ntcespecfilenm6 text,
    ntcespecfilenm7 text,
    ntcespecfilenm8 text,
    ntcespecfilenm9 text,
    ntcespecfilenm10 text,
    rbidpermsnyn text,
    pqappldocrcptmthdnm text,
    pqappldocrcptdt text,
    tpevalapplmthdnm text,
    tpevalapplclsedt text,
    jntcontrctdutyrgnnm1 text,
    jntcontrctdutyrgnnm2 text,
    jntcontrctdutyrgnnm3 text,
    rgndutyjntcontrctrt text,
    dtlsbidyn text,
    bidprtcptlmtyn text,
    prearngprcedcsnmthdnm text,
    totprdprcnum text,
    drwtprdprcnum text,
    asignbdgtamt text,
    presmptprce text,
    opengplce text,
    dcmtgoprtndt text,
    dcmtgoprtnplce text,
    bidntcedtlurl text,
    bidntceurl text,
    bidprtcptfeepaymntyn text,
    bidprtcptfee text,
    bidgrntymnypaymntyn text,
    crdtrnm text,
    ppswgnrlsrvceyn text,
    srvcedivnm text,
    prdctclsfclmtyn text,
    mnfctyn text,
    purchsobjprdctlist text,
    untyntceno text,
    cmmnspldmdmethdcd text,
    cmmnspldmdmethdnm text,
    stdntcedocurl text,
    brffcbidprcpermsnyn text,
    dsgntcmptyn text,
    arsltcmptyn text,
    pqevalyn text,
    tpevalyn text,
    ntcedscrptyn text,
    rsrvtnprceremkngmthdnm text,
    arsltappldocrcptmthdnm text,
    arsltreqstdocrcptdt text,
    orderplanuntyno text,
    sucsfbidlwltrate text,
    rgstdt text,
    bfspecrgstno text,
    infobizyn text,
    sucsfbidmthdcd text,
    sucsfbidmthdnm text,
    chgdt text,
    dminsttofclemailadrs text,
    indstrytylmtyn text,
    chgntcersn text,
    rbidopengdt text,
    vat text,
    indutyvat text,
    pubprcrmntlrgclsfcnm text,
    pubprcrmntmidclsfcnm text,
    pubprcrmntclsfcno text,
    pubprcrmntclsfcnm text,
    CONSTRAINT pk_tb_sales_annc_rel_rcv PRIMARY KEY (rel_rcv_id),
    CONSTRAINT ck_tb_sales_annc_rel_rcv_01 CHECK (reproc_cnt >= 0),
    CONSTRAINT ck_tb_sales_annc_rel_rcv_02 CHECK (rel_proc_status_cd <> 'REFLECTED' or (annc_id is not null and biz_annc_reflect_dtm is not null))
);

COMMENT ON TABLE tb_sales_annc_rel_rcv IS '조달청 OpenAPI 원본 응답 필드와 검증·반영 결과';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rel_rcv_id IS '연계 수신 건 식별자';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.collect_orgnl_id IS '수집 원문 참조 식별자';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.annc_id IS '사업공고 반영 후 설정되는 참조 식별자';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rel_proc_se_cd IS '신규 변경 취소 중복 처리 구분';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rel_proc_status_cd IS '수신 검증 반영 오류 재처리 상태';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.biz_annc_reflect_dtm IS '사업공고 반영 완료 일시';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.reproc_cnt IS '사업공고 반영 재처리 횟수';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.err_cont IS '검증 또는 반영 오류 내용';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.reg_id IS '등록자 식별자';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.reg_dtm IS '등록 일시';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.mod_id IS '수정자 식별자';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.mod_dtm IS '수정 일시';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.resultcode IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.resultmsg IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.numofrows IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pageno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.totalcount IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidntceno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidntceord IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rentceyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rgsttynm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcekindnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.intrbidyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidntcedt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.refno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidntcenm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntceinsttcd IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntceinsttnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.dminsttcd IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.dminsttnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidmethdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.cntrctcnclsmthdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntceinsttofclnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntceinsttofcltelno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntceinsttofclemailadrs IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.exctvnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidqlfctrgstdt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.cmmnspldmdagrmntrcptdocmethd IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.cmmnspldmdagrmntclsedt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.cmmnspldmdcorprgnlmtyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidbegindt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidclsedt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.opengdt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl1 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl2 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl3 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl4 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl5 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl6 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl7 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl8 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl9 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecdocurl10 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm1 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm2 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm3 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm4 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm5 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm6 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm7 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm8 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm9 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcespecfilenm10 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rbidpermsnyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pqappldocrcptmthdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pqappldocrcptdt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.tpevalapplmthdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.tpevalapplclsedt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.jntcontrctdutyrgnnm1 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.jntcontrctdutyrgnnm2 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.jntcontrctdutyrgnnm3 IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rgndutyjntcontrctrt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.dtlsbidyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidprtcptlmtyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.prearngprcedcsnmthdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.totprdprcnum IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.drwtprdprcnum IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.asignbdgtamt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.presmptprce IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.opengplce IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.dcmtgoprtndt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.dcmtgoprtnplce IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidntcedtlurl IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidntceurl IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidprtcptfeepaymntyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidprtcptfee IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bidgrntymnypaymntyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.crdtrnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ppswgnrlsrvceyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.srvcedivnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.prdctclsfclmtyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.mnfctyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.purchsobjprdctlist IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.untyntceno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.cmmnspldmdmethdcd IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.cmmnspldmdmethdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.stdntcedocurl IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.brffcbidprcpermsnyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.dsgntcmptyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.arsltcmptyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pqevalyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.tpevalyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.ntcedscrptyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rsrvtnprceremkngmthdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.arsltappldocrcptmthdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.arsltreqstdocrcptdt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.orderplanuntyno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.sucsfbidlwltrate IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rgstdt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.bfspecrgstno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.infobizyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.sucsfbidmthdcd IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.sucsfbidmthdnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.chgdt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.dminsttofclemailadrs IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.indstrytylmtyn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.chgntcersn IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.rbidopengdt IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.vat IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.indutyvat IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pubprcrmntlrgclsfcnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pubprcrmntmidclsfcnm IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pubprcrmntclsfcno IS '';
COMMENT ON COLUMN tb_sales_annc_rel_rcv.pubprcrmntclsfcnm IS '';

CREATE TABLE tb_sales_annc_oppty_rel (
    annc_oppty_rel_id varchar(26) NOT NULL,
    annc_id varchar(26) NOT NULL,
    sales_oppty_id varchar(26) NOT NULL,
    convert_user_id varchar(26) NOT NULL,
    convert_dtm timestamp DEFAULT current_timestamp,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    CONSTRAINT pk_tb_sales_annc_oppty_rel PRIMARY KEY (annc_oppty_rel_id)
);

COMMENT ON TABLE tb_sales_annc_oppty_rel IS '사업공고의 영업기회 전환 및 재공고 연결 감사정보';
COMMENT ON COLUMN tb_sales_annc_oppty_rel.annc_oppty_rel_id IS '사업공고영업기회연계의 공고영업기회연계ID';
COMMENT ON COLUMN tb_sales_annc_oppty_rel.annc_id IS '사업공고영업기회연계의 공고ID';
COMMENT ON COLUMN tb_sales_annc_oppty_rel.sales_oppty_id IS '사업공고영업기회연계의 영업기회ID';
COMMENT ON COLUMN tb_sales_annc_oppty_rel.convert_user_id IS '사업공고영업기회연계의 전환자ID';
COMMENT ON COLUMN tb_sales_annc_oppty_rel.convert_dtm IS '사업공고영업기회연계의 전환일시';
COMMENT ON COLUMN tb_sales_annc_oppty_rel.reg_id IS '사업공고영업기회연계의 등록자ID';
COMMENT ON COLUMN tb_sales_annc_oppty_rel.reg_dtm IS '사업공고영업기회연계의 등록일시';

CREATE TABLE tb_sales_oppty (
    sales_oppty_id varchar(26) NOT NULL,
    cust_id varchar(26) NOT NULL,
    oppty_nm varchar(200) NOT NULL,
    sales_stage_cd varchar(20) NOT NULL,
    est_amt numeric(15,2),
    contact_id varchar(26) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    task_tgt_id varchar(26) NOT NULL,
    CONSTRAINT pk_tb_sales_oppty PRIMARY KEY (sales_oppty_id),
    CONSTRAINT ck_tb_sales_oppty_01 CHECK (est_amt is null or est_amt >= 0),
    CONSTRAINT ck_tb_sales_oppty_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sales_oppty IS '최초 공고부터 재공고와 최종 수주까지 이어지는 영업 단위';
COMMENT ON COLUMN tb_sales_oppty.sales_oppty_id IS '영업기회의 영업기회ID';
COMMENT ON COLUMN tb_sales_oppty.cust_id IS '영업기회의 고객ID';
COMMENT ON COLUMN tb_sales_oppty.oppty_nm IS '영업기회의 명칭';
COMMENT ON COLUMN tb_sales_oppty.sales_stage_cd IS '영업기회의 현재 진행 단계 코드';
COMMENT ON COLUMN tb_sales_oppty.est_amt IS '영업기회의 예상 계약 금액';
COMMENT ON COLUMN tb_sales_oppty.contact_id IS '영업기회를 담당하는 사용자 식별자';
COMMENT ON COLUMN tb_sales_oppty.reg_id IS '영업기회의 등록자ID';
COMMENT ON COLUMN tb_sales_oppty.reg_dtm IS '영업기회의 등록일시';
COMMENT ON COLUMN tb_sales_oppty.mod_id IS '영업기회의 수정자ID';
COMMENT ON COLUMN tb_sales_oppty.mod_dtm IS '영업기회의 수정일시';
COMMENT ON COLUMN tb_sales_oppty.del_yn IS '영업기회의 삭제여부';
COMMENT ON COLUMN tb_sales_oppty.task_tgt_id IS '영업기회의 공통 기능 연결 업무대상 식별자';

CREATE TABLE tb_sales_feas_analysis (
    analysis_id varchar(26) NOT NULL,
    sales_oppty_id varchar(26) NOT NULL,
    est_rev_amt numeric(15,2),
    est_cost_amt numeric(15,2),
    est_profit_amt numeric(15,2),
    est_assign_mm numeric(6,2),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sales_feas_analysis PRIMARY KEY (analysis_id),
    CONSTRAINT ck_tb_sales_feas_analysis_01 CHECK ((est_rev_amt is null or est_rev_amt >= 0) and (est_cost_amt is null or est_cost_amt >= 0) and (est_assign_mm is null or est_assign_mm >= 0)),
    CONSTRAINT ck_tb_sales_feas_analysis_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sales_feas_analysis IS '영업기회별 예상매출 예상원가 예상손익 및 투입 분석';
COMMENT ON COLUMN tb_sales_feas_analysis.analysis_id IS '사업성분석 식별자';
COMMENT ON COLUMN tb_sales_feas_analysis.sales_oppty_id IS '사업성분석의 영업기회ID';
COMMENT ON COLUMN tb_sales_feas_analysis.est_rev_amt IS '사업성분석에서 추정한 매출 금액';
COMMENT ON COLUMN tb_sales_feas_analysis.est_cost_amt IS '사업성분석에서 추정한 원가 금액';
COMMENT ON COLUMN tb_sales_feas_analysis.est_profit_amt IS '예상매출금액에서 예상원가금액을 차감한 예상 손익 금액';
COMMENT ON COLUMN tb_sales_feas_analysis.est_assign_mm IS '사업 수행에 필요할 것으로 예상한 인력 투입량';
COMMENT ON COLUMN tb_sales_feas_analysis.reg_id IS '사업성분석의 등록자ID';
COMMENT ON COLUMN tb_sales_feas_analysis.reg_dtm IS '사업성분석의 등록일시';
COMMENT ON COLUMN tb_sales_feas_analysis.mod_id IS '사업성분석의 수정자ID';
COMMENT ON COLUMN tb_sales_feas_analysis.mod_dtm IS '사업성분석의 수정일시';
COMMENT ON COLUMN tb_sales_feas_analysis.del_yn IS '사업성분석의 삭제여부';

CREATE TABLE tb_sales_prpsl (
    prpsl_id varchar(26) NOT NULL,
    annc_id varchar(26) NOT NULL,
    prpsl_nm varchar(200) NOT NULL,
    submit_dt date,
    prsnt_dt date,
    prpsl_status_cd varchar(20) NOT NULL,
    prpsl_result_cd varchar(20),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    task_tgt_id varchar(26) NOT NULL,
    CONSTRAINT pk_tb_sales_prpsl PRIMARY KEY (prpsl_id),
    CONSTRAINT ck_tb_sales_prpsl_01 CHECK (prsnt_dt is null or submit_dt is null or prsnt_dt >= submit_dt),
    CONSTRAINT ck_tb_sales_prpsl_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sales_prpsl IS '사업공고별 단일 제안 제출정보';
COMMENT ON COLUMN tb_sales_prpsl.prpsl_id IS '제안 식별자';
COMMENT ON COLUMN tb_sales_prpsl.annc_id IS '제안의 공고ID';
COMMENT ON COLUMN tb_sales_prpsl.prpsl_nm IS '제안의 명칭';
COMMENT ON COLUMN tb_sales_prpsl.submit_dt IS '제안서를 제출한 날짜';
COMMENT ON COLUMN tb_sales_prpsl.prsnt_dt IS '제안 발표를 수행한 날짜';
COMMENT ON COLUMN tb_sales_prpsl.prpsl_status_cd IS '제안 업무의 현재 진행 상태 코드';
COMMENT ON COLUMN tb_sales_prpsl.prpsl_result_cd IS '제안 평가 또는 심사의 결과 코드';
COMMENT ON COLUMN tb_sales_prpsl.reg_id IS '제안의 등록자ID';
COMMENT ON COLUMN tb_sales_prpsl.reg_dtm IS '제안의 등록일시';
COMMENT ON COLUMN tb_sales_prpsl.mod_id IS '제안의 수정자ID';
COMMENT ON COLUMN tb_sales_prpsl.mod_dtm IS '제안의 수정일시';
COMMENT ON COLUMN tb_sales_prpsl.del_yn IS '제안의 삭제여부';
COMMENT ON COLUMN tb_sales_prpsl.task_tgt_id IS '제안의 공통 기능 연결 업무대상 식별자';

CREATE TABLE tb_sales_order_rcv (
    ord_rcv_id varchar(26) NOT NULL,
    prpsl_id varchar(26) NOT NULL,
    ord_rcv_yn char(1) NOT NULL,
    ord_rcv_amt numeric(15,2),
    ord_rcv_dt date,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_sales_order_rcv PRIMARY KEY (ord_rcv_id),
    CONSTRAINT ck_tb_sales_order_rcv_01 CHECK (ord_rcv_yn in ('Y','N')),
    CONSTRAINT ck_tb_sales_order_rcv_02 CHECK ((ord_rcv_yn = 'Y' and ord_rcv_amt is not null and ord_rcv_amt >= 0 and ord_rcv_dt is not null) or (ord_rcv_yn = 'N' and ord_rcv_amt is null and ord_rcv_dt is null)),
    CONSTRAINT ck_tb_sales_order_rcv_03 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_sales_order_rcv IS '최종 제안의 수주 여부와 결과';
COMMENT ON COLUMN tb_sales_order_rcv.ord_rcv_id IS '수주의 수주ID';
COMMENT ON COLUMN tb_sales_order_rcv.prpsl_id IS '제안 식별자';
COMMENT ON COLUMN tb_sales_order_rcv.ord_rcv_yn IS '제안 결과에 따라 사업을 수주했는지 여부';
COMMENT ON COLUMN tb_sales_order_rcv.ord_rcv_amt IS '수주가 확정된 금액';
COMMENT ON COLUMN tb_sales_order_rcv.ord_rcv_dt IS '사업 수주가 확정된 날짜';
COMMENT ON COLUMN tb_sales_order_rcv.reg_id IS '수주의 등록자ID';
COMMENT ON COLUMN tb_sales_order_rcv.reg_dtm IS '수주의 등록일시';
COMMENT ON COLUMN tb_sales_order_rcv.mod_id IS '수주의 수정자ID';
COMMENT ON COLUMN tb_sales_order_rcv.mod_dtm IS '수주의 수정일시';
COMMENT ON COLUMN tb_sales_order_rcv.del_yn IS '수주의 삭제여부';

CREATE TABLE tb_prj_mst (
    prj_id varchar(26) NOT NULL,
    prj_no varchar(30) NOT NULL,
    cntr_id varchar(26),
    cust_id varchar(26) NOT NULL,
    prj_nm varchar(200) NOT NULL,
    prj_type_cd varchar(20),
    start_dt date NOT NULL,
    orgnl_end_dt date NOT NULL,
    end_dt date NOT NULL,
    prj_status_cd varchar(20) DEFAULT 'PLANNED' NOT NULL,
    pm_user_id varchar(26),
    task_tgt_id varchar(26) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_prj_mst PRIMARY KEY (prj_id),
    CONSTRAINT ck_tb_prj_mst_01 CHECK (start_dt <= orgnl_end_dt and orgnl_end_dt <= end_dt),
    CONSTRAINT ck_tb_prj_mst_02 CHECK (del_yn in ('Y','N')),
    CONSTRAINT ck_tb_prj_mst_03 CHECK (prj_status_cd <> 'EXTENDED' or end_dt > orgnl_end_dt)
);

COMMENT ON TABLE tb_prj_mst IS '인력투입에서 참조하는 최소 프로젝트 기준정보';
COMMENT ON COLUMN tb_prj_mst.prj_id IS '프로젝트 식별자';
COMMENT ON COLUMN tb_prj_mst.prj_no IS '사용자가 식별하는 프로젝트 업무번호';
COMMENT ON COLUMN tb_prj_mst.cntr_id IS '향후 연결되는 계약 식별자';
COMMENT ON COLUMN tb_prj_mst.cust_id IS '프로젝트 고객사 식별자';
COMMENT ON COLUMN tb_prj_mst.prj_nm IS '프로젝트 명칭';
COMMENT ON COLUMN tb_prj_mst.prj_type_cd IS '프로젝트 유형 코드';
COMMENT ON COLUMN tb_prj_mst.start_dt IS '프로젝트 시작일자';
COMMENT ON COLUMN tb_prj_mst.orgnl_end_dt IS '등록 시 확정한 최초 종료일자';
COMMENT ON COLUMN tb_prj_mst.end_dt IS '연장을 반영한 현재 종료예정일자';
COMMENT ON COLUMN tb_prj_mst.prj_status_cd IS '계획 진행 연장 완료 취소 상태 코드';
COMMENT ON COLUMN tb_prj_mst.pm_user_id IS '프로젝트 담당 PM 사용자 식별자';
COMMENT ON COLUMN tb_prj_mst.task_tgt_id IS '프로젝트 공통 업무대상 식별자';
COMMENT ON COLUMN tb_prj_mst.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_prj_mst.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_prj_mst.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_prj_mst.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_prj_mst.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_mst (
    res_id varchar(26) NOT NULL,
    res_se_cd varchar(20) NOT NULL,
    full_nm varchar(100) NOT NULL,
    gender_cd varchar(20),
    birth_dt date,
    mobile_no varchar(20),
    email_addr varchar(100),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    task_tgt_id varchar(26) NOT NULL,
    CONSTRAINT pk_tb_res_mst PRIMARY KEY (res_id),
    CONSTRAINT ck_tb_res_mst_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_mst IS '직원과 외주인력에 공통으로 적용되는 식별자와 기본정보';
COMMENT ON COLUMN tb_res_mst.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_mst.res_se_cd IS '직원과 외주인력을 구분하는 코드';
COMMENT ON COLUMN tb_res_mst.full_nm IS '인력의 전체 이름';
COMMENT ON COLUMN tb_res_mst.gender_cd IS '인력의 성별을 나타내는 코드';
COMMENT ON COLUMN tb_res_mst.birth_dt IS '인력의 출생 일자';
COMMENT ON COLUMN tb_res_mst.mobile_no IS '인력 휴대전화번호';
COMMENT ON COLUMN tb_res_mst.email_addr IS '인력 이메일 주소';
COMMENT ON COLUMN tb_res_mst.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_mst.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_mst.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_mst.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_mst.del_yn IS '논리 삭제 여부';
COMMENT ON COLUMN tb_res_mst.task_tgt_id IS '인력의 공통 기능 연결 업무대상 식별자';

CREATE TABLE tb_res_employee (
    res_id varchar(26) NOT NULL,
    emp_no varchar(30) NOT NULL,
    hire_dt date,
    org_id varchar(26) NOT NULL,
    job_pos_cd varchar(20),
    employ_status_cd varchar(20),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_employee PRIMARY KEY (res_id),
    CONSTRAINT ck_tb_res_employee_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_employee IS '인력 중 내부 직원에게만 적용되는 현재 재직정보';
COMMENT ON COLUMN tb_res_employee.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_employee.emp_no IS '회사에서 직원에게 부여한 번호';
COMMENT ON COLUMN tb_res_employee.hire_dt IS '직원이 회사에 입사한 일자';
COMMENT ON COLUMN tb_res_employee.org_id IS '직원 소속 조직 식별자';
COMMENT ON COLUMN tb_res_employee.job_pos_cd IS '직원의 직위 코드';
COMMENT ON COLUMN tb_res_employee.employ_status_cd IS '직원의 재직 상태를 나타내는 코드';
COMMENT ON COLUMN tb_res_employee.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_employee.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_employee.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_employee.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_employee.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_outsrc (
    res_id varchar(26) NOT NULL,
    partner_vendor_id varchar(26) NOT NULL,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_outsrc PRIMARY KEY (res_id),
    CONSTRAINT ck_tb_res_outsrc_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_outsrc IS '인력 중 외부 인력에게만 적용되는 업체 소속 및 계약정보';
COMMENT ON COLUMN tb_res_outsrc.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_outsrc.partner_vendor_id IS '외주인력이 소속된 협력업체 식별자';
COMMENT ON COLUMN tb_res_outsrc.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_outsrc.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_outsrc.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_outsrc.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_outsrc.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_partner_vendor (
    partner_vendor_id varchar(26) NOT NULL,
    vendor_nm varchar(200) NOT NULL,
    biz_reg_no varchar(20) NOT NULL,
    ceo_nm varchar(100),
    tel_no varchar(20),
    sales_rep_nm varchar(100),
    sales_rep_dept_nm varchar(100),
    sales_rep_position varchar(100),
    sales_rep_contact varchar(20),
    co_intro_cont text,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_partner_vendor PRIMARY KEY (partner_vendor_id),
    CONSTRAINT ck_tb_res_partner_vendor_01 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_partner_vendor IS '외주인력이 소속되는 법인 또는 개인사업자 정보';
COMMENT ON COLUMN tb_res_partner_vendor.partner_vendor_id IS '외주인력이 소속된 협력업체 식별자';
COMMENT ON COLUMN tb_res_partner_vendor.vendor_nm IS '협력업체의 명칭';
COMMENT ON COLUMN tb_res_partner_vendor.biz_reg_no IS '사업자등록번호 값';
COMMENT ON COLUMN tb_res_partner_vendor.ceo_nm IS '협력업체 대표자 명칭';
COMMENT ON COLUMN tb_res_partner_vendor.tel_no IS '협력업체 대표 전화번호';
COMMENT ON COLUMN tb_res_partner_vendor.sales_rep_nm IS '협력업체 영업대표의 이름';
COMMENT ON COLUMN tb_res_partner_vendor.sales_rep_dept_nm IS '협력업체 영업대표의 부서 명칭';
COMMENT ON COLUMN tb_res_partner_vendor.sales_rep_position IS '협력업체 영업대표의 직급';
COMMENT ON COLUMN tb_res_partner_vendor.sales_rep_contact IS '협력업체 영업대표의 연락처';
COMMENT ON COLUMN tb_res_partner_vendor.co_intro_cont IS '협력업체 회사 소개 내용';
COMMENT ON COLUMN tb_res_partner_vendor.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_partner_vendor.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_partner_vendor.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_partner_vendor.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_partner_vendor.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_work_career (
    res_id varchar(26) NOT NULL,
    res_work_career_seq integer NOT NULL,
    work_start_dt date,
    work_end_dt date,
    co_nm varchar(200),
    chrg_task_desc varchar(500),
    dept_nm varchar(100),
    job_pos_nm varchar(100),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_work_career PRIMARY KEY (res_id, res_work_career_seq),
    CONSTRAINT ck_tb_res_work_career_01 CHECK (res_work_career_seq > 0),
    CONSTRAINT ck_tb_res_work_career_02 CHECK (work_end_dt is null or work_start_dt is null or work_end_dt >= work_start_dt),
    CONSTRAINT ck_tb_res_work_career_03 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_work_career IS '인력의 과거 회사 근무 및 담당업무 이력';
COMMENT ON COLUMN tb_res_work_career.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_work_career.res_work_career_seq IS '인력별 근무경력 순번';
COMMENT ON COLUMN tb_res_work_career.work_start_dt IS '과거 회사 근무를 시작한 일자';
COMMENT ON COLUMN tb_res_work_career.work_end_dt IS '과거 회사 근무를 종료한 일자';
COMMENT ON COLUMN tb_res_work_career.co_nm IS '인력이 근무한 회사 명칭';
COMMENT ON COLUMN tb_res_work_career.chrg_task_desc IS '사업에서 인력이 담당한 업무';
COMMENT ON COLUMN tb_res_work_career.dept_nm IS '과거 근무 당시 소속 부서 명칭';
COMMENT ON COLUMN tb_res_work_career.job_pos_nm IS '사업 참여 당시 인력의 직위';
COMMENT ON COLUMN tb_res_work_career.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_work_career.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_work_career.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_work_career.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_work_career.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_acad (
    res_id varchar(26) NOT NULL,
    res_acad_seq integer NOT NULL,
    school_nm varchar(200) NOT NULL,
    major_nm varchar(100),
    study_start_dt date,
    study_end_dt date,
    degree_nm varchar(100),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_acad PRIMARY KEY (res_id, res_acad_seq),
    CONSTRAINT ck_tb_res_acad_01 CHECK (res_acad_seq > 0),
    CONSTRAINT ck_tb_res_acad_02 CHECK (study_end_dt is null or study_start_dt is null or study_end_dt >= study_start_dt),
    CONSTRAINT ck_tb_res_acad_03 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_acad IS '인력의 학교·학과·수학기간·학위 정보';
COMMENT ON COLUMN tb_res_acad.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_acad.res_acad_seq IS '인력별 학력 순번';
COMMENT ON COLUMN tb_res_acad.school_nm IS '인력이 수학한 학교 명칭';
COMMENT ON COLUMN tb_res_acad.major_nm IS '인력이 수학한 학과 명칭';
COMMENT ON COLUMN tb_res_acad.study_start_dt IS '학교에서 수학을 시작한 일자';
COMMENT ON COLUMN tb_res_acad.study_end_dt IS '학교에서 수학을 종료한 일자';
COMMENT ON COLUMN tb_res_acad.degree_nm IS '인력이 취득한 학위 명칭';
COMMENT ON COLUMN tb_res_acad.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_acad.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_acad.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_acad.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_acad.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_edu (
    res_id varchar(26) NOT NULL,
    res_edu_seq integer NOT NULL,
    edu_crs_nm varchar(200) NOT NULL,
    edu_inst_nm varchar(200),
    edu_start_dt date,
    edu_end_dt date,
    cmpl_no varchar(30),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_edu PRIMARY KEY (res_id, res_edu_seq),
    CONSTRAINT ck_tb_res_edu_01 CHECK (res_edu_seq > 0),
    CONSTRAINT ck_tb_res_edu_02 CHECK (edu_end_dt is null or edu_start_dt is null or edu_end_dt >= edu_start_dt),
    CONSTRAINT ck_tb_res_edu_03 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_edu IS '인력이 이수한 교육과정·교육기관·교육기간 및 수료 정보';
COMMENT ON COLUMN tb_res_edu.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_edu.res_edu_seq IS '인력별 교육 이력 순번';
COMMENT ON COLUMN tb_res_edu.edu_crs_nm IS '인력이 이수한 교육과정 명칭';
COMMENT ON COLUMN tb_res_edu.edu_inst_nm IS '교육과정을 운영한 기관 명칭';
COMMENT ON COLUMN tb_res_edu.edu_start_dt IS '교육과정 시작 일자';
COMMENT ON COLUMN tb_res_edu.edu_end_dt IS '교육과정 종료 일자';
COMMENT ON COLUMN tb_res_edu.cmpl_no IS '교육과정 수료 시 발급된 번호';
COMMENT ON COLUMN tb_res_edu.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_edu.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_edu.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_edu.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_edu.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_award (
    res_id varchar(26) NOT NULL,
    res_awd_seq integer NOT NULL,
    awd_type_nm varchar(100),
    awd_inst_nm varchar(200),
    cnfr_dt date,
    basis_cont text,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_award PRIMARY KEY (res_id, res_awd_seq),
    CONSTRAINT ck_tb_res_award_01 CHECK (res_awd_seq > 0),
    CONSTRAINT ck_tb_res_award_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_award IS '인력이 수여받은 상훈의 종류·상훈기관·수여일 및 근거 정보';
COMMENT ON COLUMN tb_res_award.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_award.res_awd_seq IS '인력별 상훈 이력 순번';
COMMENT ON COLUMN tb_res_award.awd_type_nm IS '인력이 수여받은 상훈의 종류';
COMMENT ON COLUMN tb_res_award.awd_inst_nm IS '상훈을 수여한 기관 명칭';
COMMENT ON COLUMN tb_res_award.cnfr_dt IS '인력에게 상훈을 수여한 날짜';
COMMENT ON COLUMN tb_res_award.basis_cont IS '상훈을 수여한 근거 또는 공적 내용';
COMMENT ON COLUMN tb_res_award.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_award.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_award.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_award.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_award.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_skill_qual (
    res_id varchar(26) NOT NULL,
    res_skill_qual_seq integer NOT NULL,
    item_nm varchar(100),
    reg_no varchar(30),
    acq_dt date,
    issue_inst_nm varchar(200),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_skill_qual PRIMARY KEY (res_id, res_skill_qual_seq),
    CONSTRAINT ck_tb_res_skill_qual_01 CHECK (res_skill_qual_seq > 0),
    CONSTRAINT ck_tb_res_skill_qual_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_skill_qual IS '인력이 취득한 기술자격의 종목·등록번호·취득일·발급기관 정보';
COMMENT ON COLUMN tb_res_skill_qual.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_skill_qual.res_skill_qual_seq IS '인력별 기술자격 순번';
COMMENT ON COLUMN tb_res_skill_qual.item_nm IS '인력이 취득한 기술자격 종목';
COMMENT ON COLUMN tb_res_skill_qual.reg_no IS '기술자격 등록번호';
COMMENT ON COLUMN tb_res_skill_qual.acq_dt IS '기술자격을 취득한 날짜';
COMMENT ON COLUMN tb_res_skill_qual.issue_inst_nm IS '기술자격을 발급한 기관 명칭';
COMMENT ON COLUMN tb_res_skill_qual.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_skill_qual.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_skill_qual.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_skill_qual.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_skill_qual.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_skill_career (
    res_id varchar(26) NOT NULL,
    res_skill_career_seq integer NOT NULL,
    part_biz_nm varchar(200) NOT NULL,
    part_start_dt date,
    part_end_dt date,
    client_nm varchar(200),
    affil_co_nm varchar(200),
    job_pos_nm varchar(100),
    chrg_task_desc varchar(500),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_skill_career PRIMARY KEY (res_id, res_skill_career_seq),
    CONSTRAINT ck_tb_res_skill_career_01 CHECK (res_skill_career_seq > 0),
    CONSTRAINT ck_tb_res_skill_career_02 CHECK (part_end_dt is null or part_start_dt is null or part_end_dt >= part_start_dt),
    CONSTRAINT ck_tb_res_skill_career_03 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_skill_career IS '인력이 사업에 참여한 기간·발주사·소속사·직위 및 담당업무 경력정보';
COMMENT ON COLUMN tb_res_skill_career.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_skill_career.res_skill_career_seq IS '인력별 기술경력 순번';
COMMENT ON COLUMN tb_res_skill_career.part_biz_nm IS '인력이 참여한 사업 명칭';
COMMENT ON COLUMN tb_res_skill_career.part_start_dt IS '사업 참여 시작 일자';
COMMENT ON COLUMN tb_res_skill_career.part_end_dt IS '사업 참여 종료 일자';
COMMENT ON COLUMN tb_res_skill_career.client_nm IS '참여 사업을 발주한 회사 또는 기관 명칭';
COMMENT ON COLUMN tb_res_skill_career.affil_co_nm IS '사업 참여 당시 인력이 소속된 회사 명칭';
COMMENT ON COLUMN tb_res_skill_career.job_pos_nm IS '사업 참여 당시 인력의 직위';
COMMENT ON COLUMN tb_res_skill_career.chrg_task_desc IS '사업에서 인력이 담당한 업무';
COMMENT ON COLUMN tb_res_skill_career.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_skill_career.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_skill_career.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_skill_career.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_skill_career.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_unit_amt (
    res_unit_amt_id varchar(26) NOT NULL,
    res_id varchar(26) NOT NULL,
    base_ym char(6) NOT NULL,
    mon_unit_amt numeric(15,2),
    day_unit_amt numeric(15,2),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_unit_amt PRIMARY KEY (res_unit_amt_id),
    CONSTRAINT ck_tb_res_unit_amt_01 CHECK ((mon_unit_amt is not null or day_unit_amt is not null) and (mon_unit_amt is null or mon_unit_amt >= 0) and (day_unit_amt is null or day_unit_amt >= 0)),
    CONSTRAINT ck_tb_res_unit_amt_02 CHECK (base_ym ~ '^[0-9]{4}(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_tb_res_unit_amt_03 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_unit_amt IS '인력별 기준연월 및 월·일 단가 정보';
COMMENT ON COLUMN tb_res_unit_amt.res_unit_amt_id IS '인력 단가 이력 식별자';
COMMENT ON COLUMN tb_res_unit_amt.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_unit_amt.base_ym IS '단가와 투입실적을 적용하는 기준 연월';
COMMENT ON COLUMN tb_res_unit_amt.mon_unit_amt IS '월 기준 인력 단가';
COMMENT ON COLUMN tb_res_unit_amt.day_unit_amt IS '일 기준 인력 단가';
COMMENT ON COLUMN tb_res_unit_amt.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_unit_amt.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_unit_amt.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_unit_amt.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_unit_amt.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_assign (
    res_assign_id varchar(26) NOT NULL,
    prj_id varchar(26) NOT NULL,
    res_id varchar(26) NOT NULL,
    assign_start_dt date NOT NULL,
    assign_end_dt date,
    prj_role_cd varchar(20),
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_assign PRIMARY KEY (res_assign_id),
    CONSTRAINT ck_tb_res_assign_01 CHECK (assign_end_dt is null or assign_end_dt >= assign_start_dt),
    CONSTRAINT ck_tb_res_assign_02 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_assign IS '프로젝트별 인력 투입기간과 역할 정보';
COMMENT ON COLUMN tb_res_assign.res_assign_id IS '프로젝트별 인력 투입 식별자';
COMMENT ON COLUMN tb_res_assign.prj_id IS '프로젝트 식별자';
COMMENT ON COLUMN tb_res_assign.res_id IS '직원과 외주인력을 통합한 인력 식별자';
COMMENT ON COLUMN tb_res_assign.assign_start_dt IS '프로젝트 인력 투입 시작 일자';
COMMENT ON COLUMN tb_res_assign.assign_end_dt IS '프로젝트 인력 투입 종료 일자';
COMMENT ON COLUMN tb_res_assign.prj_role_cd IS '프로젝트에서 인력이 수행하는 역할 코드';
COMMENT ON COLUMN tb_res_assign.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_assign.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_assign.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_assign.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_assign.del_yn IS '논리 삭제 여부';

CREATE TABLE tb_res_mthly_assign_actl (
    res_mthly_assign_actl_id varchar(26) NOT NULL,
    res_assign_id varchar(26) NOT NULL,
    base_ym char(6) NOT NULL,
    plan_assign_rate numeric(5,2),
    plan_assign_mm numeric(6,2),
    actl_assign_rate numeric(5,2),
    actl_assign_mm numeric(6,2),
    actl_cnfm_yn char(1) DEFAULT 'N' NOT NULL,
    actl_cnfm_id varchar(26),
    actl_cnfm_dtm timestamp,
    remark_cont text,
    reg_id varchar(26) NOT NULL,
    reg_dtm timestamp DEFAULT current_timestamp NOT NULL,
    mod_id varchar(26),
    mod_dtm timestamp,
    del_yn char(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_tb_res_mthly_assign_actl PRIMARY KEY (res_mthly_assign_actl_id),
    CONSTRAINT ck_tb_res_mthly_assign_actl_01 CHECK (base_ym ~ '^[0-9]{4}(0[1-9]|1[0-2])$'),
    CONSTRAINT ck_tb_res_mthly_assign_actl_02 CHECK ((plan_assign_rate is null or plan_assign_rate between 0 and 100) and (actl_assign_rate is null or actl_assign_rate between 0 and 100)),
    CONSTRAINT ck_tb_res_mthly_assign_actl_03 CHECK ((plan_assign_mm is null or plan_assign_mm >= 0) and (actl_assign_mm is null or actl_assign_mm >= 0)),
    CONSTRAINT ck_tb_res_mthly_assign_actl_04 CHECK (actl_cnfm_yn in ('Y','N')),
    CONSTRAINT ck_tb_res_mthly_assign_actl_05 CHECK ((actl_cnfm_yn = 'Y' and actl_cnfm_id is not null and actl_cnfm_dtm is not null) or (actl_cnfm_yn = 'N' and actl_cnfm_id is null and actl_cnfm_dtm is null)),
    CONSTRAINT ck_tb_res_mthly_assign_actl_06 CHECK (del_yn in ('Y','N'))
);

COMMENT ON TABLE tb_res_mthly_assign_actl IS '인력투입 건의 월별 계획·실적 투입률과 투입MM 정보';
COMMENT ON COLUMN tb_res_mthly_assign_actl.res_mthly_assign_actl_id IS '인력의 월별 투입실적 식별자';
COMMENT ON COLUMN tb_res_mthly_assign_actl.res_assign_id IS '프로젝트별 인력 투입 식별자';
COMMENT ON COLUMN tb_res_mthly_assign_actl.base_ym IS '단가와 투입실적을 적용하는 기준 연월';
COMMENT ON COLUMN tb_res_mthly_assign_actl.plan_assign_rate IS '월별로 계획한 인력 투입 비율';
COMMENT ON COLUMN tb_res_mthly_assign_actl.plan_assign_mm IS '월별로 계획한 인력 투입 맨먼스';
COMMENT ON COLUMN tb_res_mthly_assign_actl.actl_assign_rate IS '월별 실제 인력 투입 비율';
COMMENT ON COLUMN tb_res_mthly_assign_actl.actl_assign_mm IS '월별로 실제 투입한 맨먼스';
COMMENT ON COLUMN tb_res_mthly_assign_actl.actl_cnfm_yn IS '월별 투입실적의 확정 여부';
COMMENT ON COLUMN tb_res_mthly_assign_actl.actl_cnfm_id IS '월별 투입실적을 확정한 사용자 식별자';
COMMENT ON COLUMN tb_res_mthly_assign_actl.actl_cnfm_dtm IS '월별 투입실적을 확정한 일시';
COMMENT ON COLUMN tb_res_mthly_assign_actl.remark_cont IS '추가 참고 내용';
COMMENT ON COLUMN tb_res_mthly_assign_actl.reg_id IS '최초 등록자 식별자';
COMMENT ON COLUMN tb_res_mthly_assign_actl.reg_dtm IS '최초 등록 일시';
COMMENT ON COLUMN tb_res_mthly_assign_actl.mod_id IS '최종 수정자 식별자';
COMMENT ON COLUMN tb_res_mthly_assign_actl.mod_dtm IS '최종 수정 일시';
COMMENT ON COLUMN tb_res_mthly_assign_actl.del_yn IS '논리 삭제 여부';
