-- Generated by scripts/generate_initial_ddl.py. Do not edit by hand.
-- Only DATABASE/Y foreign keys are materialized.

ALTER TABLE tb_sys_user_role_rel
    ADD CONSTRAINT fk_tb_sys_user_role_rel_01
    FOREIGN KEY (user_id)
    REFERENCES tb_sys_user (user_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sys_user_role_rel
    ADD CONSTRAINT fk_tb_sys_user_role_rel_02
    FOREIGN KEY (role_id)
    REFERENCES tb_sys_role (role_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sys_role_menu_perm_rel
    ADD CONSTRAINT fk_tb_sys_role_menu_perm_rel_1
    FOREIGN KEY (role_id)
    REFERENCES tb_sys_role (role_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sys_role_menu_perm_rel
    ADD CONSTRAINT fk_tb_sys_role_menu_perm_rel_2
    FOREIGN KEY (menu_id)
    REFERENCES tb_sys_menu (menu_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_com_code
    ADD CONSTRAINT fk_tb_com_code_01
    FOREIGN KEY (cd_grp_id)
    REFERENCES tb_com_code_grp (cd_grp_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_com_file
    ADD CONSTRAINT fk_tb_com_file_01
    FOREIGN KEY (task_tgt_id)
    REFERENCES tb_com_task_tgt (task_tgt_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_com_memo
    ADD CONSTRAINT fk_tb_com_memo_01
    FOREIGN KEY (task_tgt_id)
    REFERENCES tb_com_task_tgt (task_tgt_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_annc
    ADD CONSTRAINT fk_tb_sales_annc_01
    FOREIGN KEY (orgnl_annc_id)
    REFERENCES tb_sales_annc (annc_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_annc
    ADD CONSTRAINT fk_tb_sales_annc_03
    FOREIGN KEY (task_tgt_id)
    REFERENCES tb_com_task_tgt (task_tgt_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_annc_oppty_rel
    ADD CONSTRAINT fk_tb_sales_annc_oppty_rel_01
    FOREIGN KEY (annc_id)
    REFERENCES tb_sales_annc (annc_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_annc_oppty_rel
    ADD CONSTRAINT fk_tb_sales_annc_oppty_rel_02
    FOREIGN KEY (sales_oppty_id)
    REFERENCES tb_sales_oppty (sales_oppty_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_oppty
    ADD CONSTRAINT fk_tb_sales_oppty_03
    FOREIGN KEY (task_tgt_id)
    REFERENCES tb_com_task_tgt (task_tgt_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_feas_analysis
    ADD CONSTRAINT fk_tb_sales_feas_analysis_01
    FOREIGN KEY (sales_oppty_id)
    REFERENCES tb_sales_oppty (sales_oppty_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_prpsl
    ADD CONSTRAINT fk_tb_sales_prpsl_01
    FOREIGN KEY (annc_id)
    REFERENCES tb_sales_annc (annc_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_prpsl
    ADD CONSTRAINT fk_tb_sales_prpsl_02
    FOREIGN KEY (task_tgt_id)
    REFERENCES tb_com_task_tgt (task_tgt_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_sales_order_rcv
    ADD CONSTRAINT fk_tb_sales_order_rcv_01
    FOREIGN KEY (prpsl_id)
    REFERENCES tb_sales_prpsl (prpsl_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_prj_mst
    ADD CONSTRAINT fk_tb_prj_mst_04
    FOREIGN KEY (task_tgt_id)
    REFERENCES tb_com_task_tgt (task_tgt_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_mst
    ADD CONSTRAINT fk_tb_res_mst_01
    FOREIGN KEY (task_tgt_id)
    REFERENCES tb_com_task_tgt (task_tgt_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_employee
    ADD CONSTRAINT fk_tb_res_employee_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_outsrc
    ADD CONSTRAINT fk_tb_res_outsrc_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_work_career
    ADD CONSTRAINT fk_tb_res_work_career_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_acad
    ADD CONSTRAINT fk_tb_res_acad_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_edu
    ADD CONSTRAINT fk_tb_res_edu_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_award
    ADD CONSTRAINT fk_tb_res_award_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_skill_qual
    ADD CONSTRAINT fk_tb_res_skill_qual_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_skill_career
    ADD CONSTRAINT fk_tb_res_skill_career_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_unit_amt
    ADD CONSTRAINT fk_tb_res_unit_amt_01
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_assign
    ADD CONSTRAINT fk_tb_res_assign_01
    FOREIGN KEY (prj_id)
    REFERENCES tb_prj_mst (prj_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_assign
    ADD CONSTRAINT fk_tb_res_assign_02
    FOREIGN KEY (res_id)
    REFERENCES tb_res_mst (res_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;

ALTER TABLE tb_res_mthly_assign_actl
    ADD CONSTRAINT fk_tb_res_mthly_assign_actl_01
    FOREIGN KEY (res_assign_id)
    REFERENCES tb_res_assign (res_assign_id)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT;
