-- Generated by scripts/generate_initial_ddl.py. Do not edit by hand.
-- Source: physical-model index catalogs.

CREATE UNIQUE INDEX ux_tb_sys_user_01
    ON tb_sys_user USING btree (login_id);

CREATE UNIQUE INDEX ux_tb_sys_user_02
    ON tb_sys_user USING btree (emp_id)
    WHERE emp_id is not null and del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sys_role_01
    ON tb_sys_role USING btree (role_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sys_user_role_rel_01
    ON tb_sys_user_role_rel USING btree (role_id);

CREATE INDEX ix_tb_sys_menu_01
    ON tb_sys_menu USING btree (up_menu_id, sort_seq)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sys_role_menu_perm_rel_1
    ON tb_sys_role_menu_perm_rel USING btree (menu_id);

CREATE INDEX ix_tb_sys_org_01
    ON tb_sys_org USING btree (up_org_id)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_com_code_01
    ON tb_com_code USING btree (cd_grp_id, sort_seq)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sys_config_01
    ON tb_sys_config USING btree (sys_config_key)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sys_ext_rel_config_01
    ON tb_sys_ext_rel_config USING btree (ext_sys_cd)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sys_api_call_log_01
    ON tb_sys_api_call_log USING btree (ext_rel_config_id, call_start_dtm);

CREATE INDEX ix_tb_sys_api_call_log_02
    ON tb_sys_api_call_log USING btree (collect_hist_id, call_start_dtm);

CREATE INDEX ix_tb_sys_api_call_log_03
    ON tb_sys_api_call_log USING btree (call_start_dtm);

CREATE INDEX ix_tb_sys_api_call_log_04
    ON tb_sys_api_call_log USING btree (api_call_result_cd, call_start_dtm);

CREATE INDEX ix_tb_sys_api_call_log_05
    ON tb_sys_api_call_log USING btree (reproc_status_cd, call_start_dtm);

CREATE INDEX ix_tb_sys_access_log_01
    ON tb_sys_access_log USING btree (user_id, access_dtm);

CREATE INDEX ix_tb_sys_access_log_02
    ON tb_sys_access_log USING btree (access_dtm);

CREATE INDEX ix_tb_sys_access_log_03
    ON tb_sys_access_log USING btree (req_trace_id);

CREATE INDEX ix_tb_sys_log_01
    ON tb_sys_log USING btree (log_type_cd, occur_dtm);

CREATE INDEX ix_tb_sys_log_02
    ON tb_sys_log USING btree (proc_user_id, occur_dtm);

CREATE INDEX ix_tb_sys_log_03
    ON tb_sys_log USING btree (occur_dtm);

CREATE INDEX ix_tb_sys_log_04
    ON tb_sys_log USING btree (event_type_cd, occur_dtm);

CREATE INDEX ix_tb_sys_log_05
    ON tb_sys_log USING btree (tgt_type_cd, tgt_id, occur_dtm);

CREATE INDEX ix_tb_sys_log_06
    ON tb_sys_log USING btree (req_trace_id);

CREATE INDEX ix_tb_sys_notice_01
    ON tb_sys_notice USING btree (post_start_dt, post_end_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_com_noti_01
    ON tb_com_noti USING btree (rcvr_id, read_yn, occur_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_com_noti_02
    ON tb_com_noti USING btree (occur_dtm);

CREATE INDEX ix_tb_com_task_tgt_01
    ON tb_com_task_tgt USING btree (task_tgt_type_cd, reg_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_com_file_01
    ON tb_com_file USING btree (task_tgt_id, reg_dtm)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_com_file_01
    ON tb_com_file USING btree (file_path, save_file_nm);

CREATE INDEX ix_tb_com_memo_01
    ON tb_com_memo USING btree (task_tgt_id, wrt_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_com_memo_02
    ON tb_com_memo USING btree (wrtr_id, wrt_dtm)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_cust_mst_01
    ON tb_cust_mst USING btree (biz_reg_no)
    WHERE biz_reg_no is not null;

CREATE INDEX ix_tb_cust_mst_01
    ON tb_cust_mst USING btree (cust_status_cd, cust_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_cust_mst_02
    ON tb_cust_mst USING btree (cust_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_cust_contact_01
    ON tb_cust_contact USING btree (cust_id, cust_contact_status_cd, cust_contact_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_cust_contact_02
    ON tb_cust_contact USING btree (email_addr)
    WHERE del_yn = 'N' and email_addr is not null;

CREATE INDEX ix_tb_cust_activity_01
    ON tb_cust_activity USING btree (cust_id, act_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_cust_activity_02
    ON tb_cust_activity USING btree (cust_contact_id, act_dtm)
    WHERE del_yn = 'N' and cust_contact_id is not null;

CREATE INDEX ix_tb_cust_activity_03
    ON tb_cust_activity USING btree (act_chrg_user_id, act_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_cust_activity_04
    ON tb_cust_activity USING btree (act_type_cd, act_dtm)
    WHERE del_yn = 'N' and act_type_cd is not null;

CREATE UNIQUE INDEX ux_tb_sales_annc_01
    ON tb_sales_annc USING btree (bid_annc_no, bid_annc_ord)
    WHERE bid_annc_no is not null;

CREATE UNIQUE INDEX ux_tb_sales_annc_02
    ON tb_sales_annc USING btree (task_tgt_id);

CREATE INDEX ix_tb_sales_annc_01
    ON tb_sales_annc USING btree (demand_inst_nm, bid_start_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_02
    ON tb_sales_annc USING btree (annc_status_cd, bid_start_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_03
    ON tb_sales_annc USING btree (annc_review_status_cd, reg_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_04
    ON tb_sales_annc USING btree (orgnl_annc_id)
    WHERE del_yn = 'N' and orgnl_annc_id is not null;

CREATE INDEX ix_tb_sales_annc_05
    ON tb_sales_annc USING btree (bid_prgrs_status_cd, bid_result_cd, result_cnfm_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_06
    ON tb_sales_annc USING btree (annc_nm)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sales_annc_collect_cond_01
    ON tb_sales_annc_collect_cond USING btree (collect_cond_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_collect_cond_01
    ON tb_sales_annc_collect_cond USING btree (annc_biz_se_cd, last_succ_collect_dtm)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sales_annc_collect_tgt_inst_01
    ON tb_sales_annc_collect_tgt_inst USING btree (collect_cond_id, order_inst_cd)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_collect_tgt_inst_01
    ON tb_sales_annc_collect_tgt_inst USING btree (collect_cond_id, order_inst_nm)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sales_annc_collect_kwd_01
    ON tb_sales_annc_collect_kwd USING btree (collect_cond_id, kwd_se_cd, kwd_cont)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_collect_kwd_01
    ON tb_sales_annc_collect_kwd USING btree (collect_cond_id, kwd_se_cd)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_annc_collect_hist_01
    ON tb_sales_annc_collect_hist USING btree (collect_cond_id, collect_start_dtm);

CREATE INDEX ix_tb_sales_annc_collect_hist_02
    ON tb_sales_annc_collect_hist USING btree (collect_proc_status_cd, collect_start_dtm);

CREATE INDEX ix_tb_sales_annc_collect_hist_03
    ON tb_sales_annc_collect_hist USING btree (reproc_status_cd, collect_start_dtm);

CREATE INDEX ix_tb_sales_annc_collect_hist_04
    ON tb_sales_annc_collect_hist USING btree (reg_dtm);

CREATE UNIQUE INDEX ux_tb_sales_annc_collect_orgnl_01
    ON tb_sales_annc_collect_orgnl USING btree (collect_hist_id, bid_annc_no, bid_annc_ord, orgnl_hash_val);

CREATE INDEX ix_tb_sales_annc_collect_orgnl_01
    ON tb_sales_annc_collect_orgnl USING btree (bid_annc_no, bid_annc_ord, collect_dtm);

CREATE INDEX ix_tb_sales_annc_collect_orgnl_02
    ON tb_sales_annc_collect_orgnl USING btree (orgnl_hash_val);

CREATE UNIQUE INDEX ux_tb_sales_annc_rel_rcv_01
    ON tb_sales_annc_rel_rcv USING btree (collect_orgnl_id);

CREATE INDEX ix_tb_sales_annc_rel_rcv_01
    ON tb_sales_annc_rel_rcv USING btree (rel_proc_status_cd, reg_dtm);

CREATE INDEX ix_tb_sales_annc_rel_rcv_02
    ON tb_sales_annc_rel_rcv USING btree (annc_id, reg_dtm)
    WHERE annc_id is not null;

CREATE INDEX ix_tb_sales_annc_rel_rcv_03
    ON tb_sales_annc_rel_rcv USING btree (bidntceno, bidntceord, chgdt);

CREATE UNIQUE INDEX ux_tb_sales_annc_oppty_rel_01
    ON tb_sales_annc_oppty_rel USING btree (annc_id);

CREATE INDEX ix_tb_sales_annc_oppty_rel_01
    ON tb_sales_annc_oppty_rel USING btree (sales_oppty_id, convert_dtm);

CREATE UNIQUE INDEX ux_tb_sales_oppty_01
    ON tb_sales_oppty USING btree (task_tgt_id);

CREATE INDEX ix_tb_sales_oppty_01
    ON tb_sales_oppty USING btree (cust_id, sales_stage_cd, reg_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_oppty_02
    ON tb_sales_oppty USING btree (contact_id, sales_stage_cd, reg_dtm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_sales_oppty_03
    ON tb_sales_oppty USING btree (oppty_nm)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sales_feas_analysis_01
    ON tb_sales_feas_analysis USING btree (sales_oppty_id)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sales_prpsl_01
    ON tb_sales_prpsl USING btree (annc_id);

CREATE UNIQUE INDEX ux_tb_sales_prpsl_02
    ON tb_sales_prpsl USING btree (task_tgt_id);

CREATE INDEX ix_tb_sales_prpsl_01
    ON tb_sales_prpsl USING btree (prpsl_status_cd, submit_dt)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_sales_order_rcv_01
    ON tb_sales_order_rcv USING btree (prpsl_id);

CREATE INDEX ix_tb_sales_order_rcv_01
    ON tb_sales_order_rcv USING btree (ord_rcv_yn, ord_rcv_dt)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_prj_mst_01
    ON tb_prj_mst USING btree (prj_no);

CREATE UNIQUE INDEX ux_tb_prj_mst_02
    ON tb_prj_mst USING btree (task_tgt_id);

CREATE INDEX ix_tb_prj_mst_01
    ON tb_prj_mst USING btree (cust_id, prj_status_cd, prj_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_prj_mst_02
    ON tb_prj_mst USING btree (prj_status_cd, end_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_prj_mst_03
    ON tb_prj_mst USING btree (pm_user_id, prj_status_cd)
    WHERE del_yn = 'N' and pm_user_id is not null;

CREATE UNIQUE INDEX ux_tb_res_mst_01
    ON tb_res_mst USING btree (task_tgt_id);

CREATE INDEX ix_tb_res_mst_01
    ON tb_res_mst USING btree (res_se_cd, full_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_mst_02
    ON tb_res_mst USING btree (mobile_no)
    WHERE del_yn = 'N' and mobile_no is not null;

CREATE UNIQUE INDEX ux_tb_res_employee_01
    ON tb_res_employee USING btree (emp_no);

CREATE INDEX ix_tb_res_employee_01
    ON tb_res_employee USING btree (org_id, employ_status_cd)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_employee_02
    ON tb_res_employee USING btree (hire_dt)
    WHERE del_yn = 'N' and hire_dt is not null;

CREATE INDEX ix_tb_res_outsrc_01
    ON tb_res_outsrc USING btree (partner_vendor_id, res_id)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_res_partner_vendor_01
    ON tb_res_partner_vendor USING btree (biz_reg_no)
    WHERE biz_reg_no is not null;

CREATE INDEX ix_tb_res_partner_vendor_01
    ON tb_res_partner_vendor USING btree (vendor_nm)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_work_career_01
    ON tb_res_work_career USING btree (res_id, work_start_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_acad_01
    ON tb_res_acad USING btree (res_id, study_start_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_edu_01
    ON tb_res_edu USING btree (res_id, edu_start_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_award_01
    ON tb_res_award USING btree (res_id, cnfr_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_skill_qual_01
    ON tb_res_skill_qual USING btree (res_id, acq_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_skill_career_01
    ON tb_res_skill_career USING btree (res_id, part_start_dt)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_res_unit_amt_01
    ON tb_res_unit_amt USING btree (res_id, base_ym)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_unit_amt_01
    ON tb_res_unit_amt USING btree (base_ym, res_id)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_assign_01
    ON tb_res_assign USING btree (prj_id, assign_start_dt, assign_end_dt)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_assign_02
    ON tb_res_assign USING btree (res_id, assign_start_dt, assign_end_dt)
    WHERE del_yn = 'N';

CREATE UNIQUE INDEX ux_tb_res_mthly_assign_actl_01
    ON tb_res_mthly_assign_actl USING btree (res_assign_id, base_ym)
    WHERE del_yn = 'N';

CREATE INDEX ix_tb_res_mthly_assign_actl_01
    ON tb_res_mthly_assign_actl USING btree (base_ym, actl_cnfm_yn)
    WHERE del_yn = 'N';
