#!/usr/bin/env python3
"""Generate the immutable initial PostgreSQL Flyway DDL from physical-model CSVs."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path


AREAS = ("system", "common", "customer", "sales", "project", "employee")
TABLE_MIGRATION = "V202607221000__create_initial_tables.sql"
FK_MIGRATION = "V202607221010__add_initial_foreign_keys.sql"
INDEX_MIGRATION = "V202607221020__create_initial_indexes.sql"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as stream:
        return list(csv.DictReader(stream))


def sql_name(value: str) -> str:
    """Render a catalog identifier as an unquoted PostgreSQL identifier."""
    return value.strip().lower()


def sql_expression(value: str) -> str:
    """Lowercase identifiers and keywords without changing string literals."""
    result: list[str] = []
    in_string = False
    index = 0
    while index < len(value):
        char = value[index]
        if char == "'":
            result.append(char)
            if in_string and index + 1 < len(value) and value[index + 1] == "'":
                result.append("'")
                index += 2
                continue
            in_string = not in_string
        else:
            result.append(char if in_string else char.lower())
        index += 1
    if in_string:
        raise ValueError(f"Unterminated SQL string literal: {value}")
    return "".join(result)


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def column_list(value: str) -> str:
    return ", ".join(sql_name(item) for item in value.split("|") if item)


def load_area_rows(root: Path, kind: str) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    singular = {"tables": "table", "columns": "column", "constraints": "constraint", "indexes": "index"}[kind]
    for area in AREAS:
        rows.extend(read_csv(root / kind / f"{singular}-{area}.csv"))
    return rows


def render_tables(
    tables: list[dict[str, str]],
    columns: list[dict[str, str]],
    constraints: list[dict[str, str]],
    type_mapping: dict[str, str],
) -> str:
    columns_by_table: dict[str, list[dict[str, str]]] = defaultdict(list)
    constraints_by_table: dict[str, list[dict[str, str]]] = defaultdict(list)
    for column in columns:
        columns_by_table[column["table_name"]].append(column)
    for constraint in constraints:
        if (
            constraint["create_yn"] == "Y"
            and constraint["enforcement_type"] == "DATABASE"
            and constraint["constraint_type"] in {"PK", "UK", "CK"}
        ):
            constraints_by_table[constraint["table_name"]].append(constraint)

    output = [
        "-- Generated by scripts/generate_initial_ddl.py. Do not edit by hand.",
        "-- Source: docs/02.architecture/02.data-architecture/03.physical-model",
        "",
    ]
    for table in tables:
        catalog_name = table["table_name"]
        table_columns = sorted(
            columns_by_table[catalog_name], key=lambda row: int(row["column_sequence"])
        )
        if not table_columns:
            raise ValueError(f"No columns found for {catalog_name}")

        definitions: list[str] = []
        for column in table_columns:
            data_type = column["data_type_override"] or type_mapping.get(column["domain_name"])
            if not data_type:
                raise ValueError(
                    f"No PostgreSQL type for {catalog_name}.{column['column_name']} "
                    f"domain {column['domain_name']}"
                )
            definition = f"    {sql_name(column['column_name'])} {data_type.lower()}"
            if column["default_value"]:
                definition += f" DEFAULT {sql_expression(column['default_value'])}"
            if column["nullable"] == "N":
                definition += " NOT NULL"
            definitions.append(definition)

        for constraint in constraints_by_table[catalog_name]:
            constraint_type = constraint["constraint_type"]
            prefix = f"    CONSTRAINT {sql_name(constraint['constraint_name'])} "
            if constraint_type == "PK":
                definition = prefix + f"PRIMARY KEY ({column_list(constraint['column_names'])})"
            elif constraint_type == "UK":
                definition = prefix + f"UNIQUE ({column_list(constraint['column_names'])})"
            else:
                definition = prefix + f"CHECK ({sql_expression(constraint['check_expression'])})"
            definitions.append(definition)

        output.append(f"CREATE TABLE {sql_name(catalog_name)} (")
        output.append(",\n".join(definitions))
        output.extend([
            ");",
            "",
            f"COMMENT ON TABLE {sql_name(catalog_name)} IS {sql_literal(table['description'])};",
        ])
        for column in table_columns:
            output.append(
                f"COMMENT ON COLUMN {sql_name(catalog_name)}.{sql_name(column['column_name'])} "
                f"IS {sql_literal(column['description'])};"
            )
        output.append("")
    return "\n".join(output).rstrip() + "\n"


def render_foreign_keys(constraints: list[dict[str, str]]) -> str:
    output = [
        "-- Generated by scripts/generate_initial_ddl.py. Do not edit by hand.",
        "-- Only DATABASE/Y foreign keys are materialized.",
        "",
    ]
    for constraint in constraints:
        if not (
            constraint["constraint_type"] == "FK"
            and constraint["enforcement_type"] == "DATABASE"
            and constraint["create_yn"] == "Y"
        ):
            continue
        statement = [
            f"ALTER TABLE {sql_name(constraint['table_name'])}",
            f"    ADD CONSTRAINT {sql_name(constraint['constraint_name'])}",
            f"    FOREIGN KEY ({column_list(constraint['column_names'])})",
            f"    REFERENCES {sql_name(constraint['reference_table'])} "
            f"({column_list(constraint['reference_columns'])})",
        ]
        if constraint["on_delete"]:
            statement.append(f"    ON DELETE {constraint['on_delete'].upper()}")
        if constraint["on_update"]:
            statement.append(f"    ON UPDATE {constraint['on_update'].upper()}")
        output.append("\n".join(statement) + ";")
        output.append("")
    return "\n".join(output).rstrip() + "\n"


def render_indexes(indexes: list[dict[str, str]]) -> str:
    output = [
        "-- Generated by scripts/generate_initial_ddl.py. Do not edit by hand.",
        "-- Source: physical-model index catalogs.",
        "",
    ]
    for index in indexes:
        unique = "UNIQUE " if index["unique_yn"] == "Y" else ""
        method = (index["index_method"] or "BTREE").lower()
        statement = (
            f"CREATE {unique}INDEX {sql_name(index['index_name'])}\n"
            f"    ON {sql_name(index['table_name'])} USING {method} "
            f"({column_list(index['column_names'])})"
        )
        if index["where_condition"]:
            statement += f"\n    WHERE {sql_expression(index['where_condition'])}"
        output.append(statement + ";")
        output.append("")
    return "\n".join(output).rstrip() + "\n"


def write_or_check(path: Path, content: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit(f"Generated migration is missing or stale: {path}")
        print(f"OK {path}")
        return
    if path.exists():
        raise SystemExit(
            f"Refusing to overwrite immutable migration: {path}\n"
            "Delete it only before it has been applied to a shared database."
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"CREATED {path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Verify generated migrations without modifying them"
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    data_root = repo_root / "docs/02.architecture/02.data-architecture"
    physical_root = data_root / "03.physical-model"
    migration_root = repo_root / "backend/src/main/resources/db/migration"

    type_rows = read_csv(data_root / "01.standard/db-type-mapping.csv")
    type_mapping = {
        row["domain_name"]: row["data_type"]
        for row in type_rows
        if row["dbms"] == "PostgreSQL"
    }
    tables = load_area_rows(physical_root, "tables")
    columns = load_area_rows(physical_root, "columns")
    constraints = load_area_rows(physical_root, "constraints")
    indexes = load_area_rows(physical_root, "indexes")

    if len(tables) != 47:
        raise SystemExit(f"Expected 47 initial tables, found {len(tables)}")

    outputs = {
        TABLE_MIGRATION: render_tables(tables, columns, constraints, type_mapping),
        FK_MIGRATION: render_foreign_keys(constraints),
        INDEX_MIGRATION: render_indexes(indexes),
    }
    for filename, content in outputs.items():
        write_or_check(migration_root / filename, content, args.check)


if __name__ == "__main__":
    main()
